# 0) IMPORTS

In [1]:
# Setup autoreload - automatically reload modules when they change
%load_ext autoreload
%autoreload 2

In [2]:
# Verify environment setup
import os
import sys

print(f"Python version: {sys.version}")
print(f"Python executable: {sys.executable}")
print(f"\nEnvironment variables loaded:")
print(f"OPENAI_API_KEY: {'✓ Set' if os.getenv('OPENAI_API_KEY') else '✗ Not set'}")
print(f"MASSIVE.COM - ex.POLYGON_API_KEY: {'✓ Set' if os.getenv('POLYGON_API_KEY') else '✗ Not set'}")
print(f"XAI_API_KEY: {'✓ Set' if os.getenv('XAI_API_KEY') else '✗ Not set'}")
print(f"SEC_IDENTITY_EMAIL: {'✓ Set' if os.getenv('SEC_IDENTITY_EMAIL') else '✗ Not set'}")

Python version: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]
Python executable: /Users/realmistic/Documents/stocks-scoring-agent/.venv/bin/python

Environment variables loaded:
OPENAI_API_KEY: ✓ Set
MASSIVE.COM - ex.POLYGON_API_KEY: ✓ Set
XAI_API_KEY: ✓ Set
SEC_IDENTITY_EMAIL: ✓ Set

# 1) TEST: Checking news retrieval for the recent 5k records 
* The datasource is Massive.com (previously known as Polygon.io)
* 2 tools defined: 
  * search_news_by_ticker (not just YahooFinance source)
  * search_news_by_query (it can find a wider set of news to expand the topic)

In [3]:
from datetime import datetime, timezone
now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
print (f'Time now = {now}')

# The exact time of running the Colab (in UTC, timezone-aware)
now_right_format = datetime.now(timezone.utc).isoformat(timespec='milliseconds')
print(f'Time now in the right format (for API) = {now_right_format}')

Time now = 2026-06-14
Time now in the right format (for API) = 2026-06-14T13:06:27.443+00:00

In [4]:
import requests
import pandas as pd
import os

# MASSIVE.COM is previously known as Polygon.io
# https://massive.com/docs/rest/stocks/news
# https://massive.com/blog/api-pagination-patterns
# API CALL : # https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&apiKey=<your key> or POLYGON_API_KEY
      # need to get 200 OK status

# check the API KEY is imported correctly from the .envrc file
print(len(f'Length of the POLYGON_API_KEY = {os.getenv("POLYGON_API_KEY")}'))

POLYGON_API_KEY = os.getenv('POLYGON_API_KEY')

# retrieve max 1000 news via one API call
def get_one_chunk_of_news_polygon_io(api_key = POLYGON_API_KEY, news_limit=1000, max_date = now):
#OLD:   url = f"https://api.polygon.io/v2/reference/news?order=desc&limit={news_limit}&sort=published_utc&published_utc.lt={max_date}&apiKey={api_key}"
  url = f"https://api.massive.com/v2/reference/news?order=desc&limit={news_limit}&sort=published_utc&published_utc.lt={max_date}&apiKey={api_key}"


  # https://www.nylas.com/blog/use-python-requests-module-rest-apis/ - Python for rest APIs
  # try/catch for HTTP requests: https://stackoverflow.com/questions/16511337/correct-way-to-try-except-using-python-requests-module
  try:
      url_sanitized = url.split("&apiKey=")[0] + "&apiKey=<your key>"
      print(f'trying the API call : {url_sanitized}')
      r = requests.get(url, timeout=3)
      r.raise_for_status()
  except requests.exceptions.HTTPError as errh:
      print ("Http Error:",errh)
  except requests.exceptions.ConnectionError as errc:
      print ("Error Connecting:",errc)
  except requests.exceptions.Timeout as errt:
      print ("Timeout Error:",errt)
  except requests.exceptions.RequestException as err:
      print ("OOps: Something Else",err)

  data = r.json()


  # Check if 'results' key exists in the response
  if 'results' in data:
      # If it exists, proceed with normalization
      df_nested_list = pd.json_normalize(data, record_path=['results'])
  else:
      # If not, print the response keys for debugging and create an empty DataFrame
      print(f"The 'results' key was not found in the response. Available keys are: {data.keys()}")
      df_nested_list = pd.DataFrame() # or handle it differently based on the new structure

  return df_nested_list

def get_all_news(api_calls_left = 5, api_key = POLYGON_API_KEY, news_limit=1000, max_date = now):
  all_news = None
  for i in range(api_calls_left):
    cur = get_one_chunk_of_news_polygon_io(api_key = api_key, news_limit = news_limit, max_date = max_date)
    if all_news is None:
      all_news = cur
    else:
      all_news = pd.concat([all_news,cur], ignore_index=True, axis=0) #stacking dataframes

    max_date = cur.published_utc.min() #update max_date of the news
  return all_news

64

In [5]:
# test getting all news
# 5 calls per minute limit for a free account - all recent news (5000)
all_news = get_all_news()

trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-06-14&apiKey=<your key>
trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-06-09T17:28:49Z&apiKey=<your key>
trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-06-04T10:00:00Z&apiKey=<your key>
trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-05-29T22:15:00Z&apiKey=<your key>
trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-05-25T18:56:00Z&apiKey=<your key>

In [6]:
all_news.head()

,id,title,author,published_utc,article_url,tickers,image_url,description,keywords,insights,publisher.name,publisher.homepage_url,publisher.logo_url,publisher.favicon_url,amp_url
0,b2f3a113f375b61f1bc288a1d08cc27adc88ef79b8482b...,"ROSEN, NATIONAL INVESTOR COUNSEL, Encourages V...",Rosen Law Firm,2026-06-13T23:50:00Z,https://www.globenewswire.com/news-release/202...,[VERI],https://ml.globenewswire.com/Resource/Download...,Rosen Law Firm is urging investors who purchas...,"[securities class action, financial restatemen...","[{'ticker': 'VERI', 'sentiment': 'negative', '...",GlobeNewswire Inc.,https://www.globenewswire.com,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN
1,8660ae9a9565114ac6b1135157c21f6d1790a3eca72b10...,"SpaceX IPO Sets the Stage, These Five Tech Com...",Crispus Nyaga,2026-06-13T23:26:37Z,https://www.benzinga.com/markets/tech/26/06/53...,"[SPCX, NVDA, ORCL, ORCLpD]",https://cdn.benzinga.com/cdn-cgi/image/width=1...,"Following SpaceX's successful $75 billion IPO,...","[IPO, SpaceX, Anthropic, OpenAI, tech companie...","[{'ticker': 'SPCX', 'sentiment': 'positive', '...",Benzinga,https://www.benzinga.com/,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN
2,4d52d542b8a2d8d73b5a0010ef06793b64124a98dc0def...,How Insurance Companies Turn Their Premiums In...,Reuben Gregg Brewer,2026-06-13T23:15:00Z,https://www.fool.com/investing/2026/06/13/how-...,"[BRK.A, BRK.B, PGR, MKL, BN, BNH, BNJ]",https://g.foolcdn.com/image/?url=https%3A%2F%2...,Insurance companies generate billions in profi...,"[insurance float, investment income, premium i...","[{'ticker': 'BRK.A', 'sentiment': 'positive', ...",The Motley Fool,https://www.fool.com/,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN
3,12b48538e163af0c55da8843aa5dab211becdac2941733...,How Safe is Bristol Myers Squibb's Dividend? H...,Reuben Gregg Brewer,2026-06-13T22:15:00Z,https://www.fool.com/investing/2026/06/13/how-...,"[BMY, CELGr, PFE]",https://g.foolcdn.com/image/?url=https%3A%2F%2...,Bristol Myers Squibb offers an attractive 4.5%...,"[dividend safety, pharmaceutical sector, paten...","[{'ticker': 'BMY', 'sentiment': 'positive', 's...",The Motley Fool,https://www.fool.com/,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN
4,9cc0eb5cf81786ffdfc025d8b10096d2087bc931635ce0...,Is Palantir Stock Ripe for a Rebound?,Adria Cimino,2026-06-13T22:10:00Z,https://www.fool.com/investing/2026/06/13/is-p...,"[PLTR, NVDA, GOOG, GOOGL, GOOGM, GOOGN]",https://g.foolcdn.com/image/?url=https%3A%2F%2...,Palantir Technologies has experienced strong r...,"[artificial intelligence, AI platform, valuati...","[{'ticker': 'PLTR', 'sentiment': 'neutral', 's...",The Motley Fool,https://www.fool.com/,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN

In [7]:
all_news_json = all_news.to_dict(orient='records')

In [8]:
len(all_news_json)

5000

In [9]:
# Key features:

#   1. No chunking needed - Each news article is already a discrete document
#   2. Text search - Searches across title, description, keywords, author
#   3. Exact ticker matching - Function to find articles with specific ticker in tickers field
#   4. Multi-ticker support - Search for multiple tickers at once
#   5. Date filtering - Can filter news by publication date
#   6. Boosting - Title matches get higher priority than description

#   Note on chunking:
#   Unlike the podcast data (long markdown documents), news articles are already atomic units. Each article is a complete piece of information, so no chunking is
#   needed. The tickers field already provides precise ticker associations.

In [10]:

# Import minsearch
from minsearch import Index

# Step 1: Convert DataFrame to list of dicts (if not already done)
news_documents = all_news.to_dict(orient='records')

print(f"Total news articles: {len(news_documents)}")
print(f"Fields per article: {len(news_documents[0])}")
print(f"Sample article keys: {list(news_documents[0].keys())}")

Total news articles: 5000
Fields per article: 15
Sample article keys: ['id', 'title', 'author', 'published_utc', 'article_url', 'tickers', 'image_url', 'description', 'keywords', 'insights', 'publisher.name', 'publisher.homepage_url', 'publisher.logo_url', 'publisher.favicon_url', 'amp_url']

In [11]:
from tqdm import tqdm
  # Step 2: Preprocess documents - convert list fields to strings
print("\nPreprocessing documents...")
for doc in tqdm(news_documents, desc="Converting fields"):
    # Convert list fields to comma-separated strings
    if isinstance(doc.get('tickers'), list):
        doc['tickers'] = ', '.join(doc['tickers'])

    if isinstance(doc.get('keywords'), list):
        doc['keywords'] = ', '.join(doc['keywords'])

    # Ensure text fields are strings
    for field in ['title', 'description', 'author']:
        if doc.get(field) is None:
            doc[field] = ''
        elif not isinstance(doc.get(field), str):
            doc[field] = str(doc[field])

print("✓ Preprocessing complete")

Preprocessing documents...

Converting fields: 100%|██████████| 5000/5000 [00:00<00:00, 777356.36it/s]

✓ Preprocessing complete

In [12]:

  # Step 3: Create Index with relevant text fields
news_index = Index(
    text_fields=["title", "description", "keywords", "author", "tickers"],
    keyword_fields=["published_utc", "publisher.name"]
)

# Step 4: Fit the index with preprocessed documents
print("\nBuilding search index...")
news_index.fit(news_documents)
print(f"✓ Index created with {len(news_documents)} articles")

Building search index...
✓ Index created with 5000 articles

In [13]:
# Step 5: Search function to retrieve news for a ticker
def search_news_by_ticker(ticker, num_results=30):
    """
      Search for news articles related to a specific ticker.
      
      Args:
          ticker: Stock ticker symbol (e.g., 'TSLA', 'AAPL')
          num_results: Number of results to return
      
      Returns:
          List of news articles matching the ticker
    """
    results = news_index.search(
        query=ticker,
        num_results=num_results,
        boost_dict={
              'tickers': 5.0,      # Highest boost for ticker field
              'title': 3.0,         # High boost for title
              'description': 1.5,   # Medium boost for description
              'keywords': 1.0       # Standard boost for keywords
          }
      )
    return results

In [14]:
# Step 6: Search function to retrieve news for a search query
def search_news_by_query(query, num_results=30):
    """
      Search for news articles related to a specific query.
      
      Args:
          query: Search query (e.g., 'Tesla', 'AI robotics')
          num_results: Number of results to return
      
      Returns:
          List of news articles matching the ticker
    """
    results = news_index.search(
        query=query,
        num_results=num_results,
        boost_dict={
              'tickers': 1.0,      # boost for ticker field
              'title': 3.0,         # High boost for title
              'description': 5,   # Highest boost for description
              'keywords': 5       # Highest boost for keywords
          }
      )
    return results

In [15]:

# Step 7: Test - Get news for TSLA
print("\n" + "="*70)
print("Testing search for TSLA...")
print("="*70)

tsla_news = search_news_by_ticker("TSLA", num_results=5)

print(f"\nFound {len(tsla_news)} news articles for TSLA:\n")
for i, article in enumerate(tsla_news, 1):
    print(f"{i}. {article['title']}")
    print(f"   Published: {article['published_utc']}")
    print(f"   Tickers: {article['tickers']}")
    print(f"   Description: {article['description'][:100]}...")
    print()

======================================================================
Testing search for TSLA...
======================================================================

Found 5 news articles for TSLA:

1. Crypto Markets Are Already Pricing SPCX: What Happens At IPO?
   Published: 2026-06-04T16:09:45Z
   Tickers: TSLA
   Description: SpaceX is preparing for a major IPO in June 2026 targeting a $1.8 trillion valuation and $70-75 bill...

2. Will SpaceX Merge With Tesla? The Answer Might Be Hiding in Plain Sight.
   Published: 2026-06-08T17:17:00Z
   Tickers: TSLA
   Description: SpaceX's updated S-1 IPO filing contains revised language suggesting the company may issue significa...

3. Tesla Investors Finally Get A Benchmark For The Musk Premium
   Published: 2026-06-01T17:19:11Z
   Tickers: TSLA
   Description: SpaceX's anticipated IPO will provide investors with a second publicly traded Musk-led company, allo...

4. Here Are 7 Important Things Investors Learned from SpaceX's S-1 Filing
   Published: 2026-05-22T21:20:00Z
   Tickers: TSLA
   Description: SpaceX filed its S-1 prospectus ahead of its IPO, seeking a $2 trillion valuation and $75 billion in...

5. Elon Musk Net Worth Could Top $1 Trillion With SpaceX IPO: Make $100 Million A Day And It Would Take This Long To Catch Him
   Published: 2026-06-08T18:43:59Z
   Tickers: TSLA
   Description: Elon Musk's net worth could exceed $1 trillion following SpaceX's anticipated IPO at a $1.75 trillio...

In [16]:
# Step 8: search news by query
print("\n" + "="*70)
print("Testing search by query...")
print("="*70)

query = "Tesla competitors analysis EV margins autonomy AI robotics China market share outlook"
tsla_competitors_news = search_news_by_query(query, num_results=25)

print(f"\nFound {len(tsla_competitors_news)} news articles for TSLA competitors:\n")
for i, article in enumerate(tsla_competitors_news, 1):
    print(f"{i}. {article['title']}")
    print(f"   Published: {article['published_utc']}")
    print(f"   Tickers: {article['tickers']}")
    print(f"   Description: {article['description'][:100]}...")
    print()

======================================================================
Testing search by query...
======================================================================

Found 25 news articles for TSLA competitors:

1. EV Sales Skyrocket: Tesla Stock Surges On 67% European Boom, Blockbuster SpaceX IPO Rumors
   Published: 2026-05-27T15:40:06Z
   Tickers: TSLA, BYDDY, GELHY
   Description: Tesla stock gained 1.11% on Wednesday, driven by strong European EV sales growth (67.2% year-over-ye...

2. Following Trump-Xi Talks, Elon Musk's Tesla Launches Full Self-Driving In China After Years Of Uncertainty
   Published: 2026-05-21T10:26:10Z
   Tickers: TSLA, BYDDY, BA, BApA
   Description: Tesla has launched its Full Self-Driving (FSD) service in China, expanding to 10 countries total, fo...

3. Tesla’s European Recovery Is Real, But BYD Defines the Limit
   Published: 2026-05-27T07:07:00Z
   Tickers: TSLA, BYDDY
   Description: Tesla shows genuine recovery in European EV registrations with three consecutive months of year-on-y...

4. Is China's EV Boom Losing Steam? Tesla Rival Nio's CEO Sounds The Alarm
   Published: 2026-05-28T12:03:08Z
   Tickers: NIO, TSLA, BYDDY
   Description: Nio CEO William Li warns that China's automotive sector has passed its 'golden era,' with domestic c...

5. Why Tesla Robotaxi Dreams Can’t Rescue Today’s Weak Fundamentals
   Published: 2026-05-28T12:36:00Z
   Tickers: TSLA, F, FpB, FpC, FpD, GM, BIDU, NIO, LI, XPEV, BYDDY
   Description: Tesla's valuation of $1.3 trillion is heavily dependent on unproven robotaxi and AI technologies, wi...

6. BYD Leads China's Global EV Push As Overseas Demand Accelerates
   Published: 2026-06-05T08:08:38Z
   Tickers: BYDDY, CRAUY, GWLLY
   Description: Chinese EV makers BYD and Chery are rapidly expanding overseas sales, with both reporting 81% year-o...

7. Should Investors Sell Tesla Stock to Buy SpaceX?
   Published: 2026-06-06T18:05:00Z
   Tickers: TSLA, GM
   Description: A potential SpaceX IPO could fundamentally reshape how investors value Tesla stock. For years, Tesla...

8. Mr. Roboto: Tap Into the Humanoid Robotics Boom With This ETF
   Published: 2026-06-03T13:12:00Z
   Tickers: KOID
   Description: The KraneShares Global Humanoid Robotics and Physical AI Index ETF (KOID) is positioned as a key inv...

9. 2 Monster EV Stocks Chasing a $10 Trillion AI Opportunity
   Published: 2026-05-29T09:30:00Z
   Tickers: TSLA, RIVN, UBER
   Description: The article highlights how EV companies are positioned to capitalize on a $10 trillion robotaxi mark...

10. How Nio Is Proving It's a Top Auto Stock Despite Brutal the Price War
   Published: 2026-06-03T17:07:00Z
   Tickers: NIO, BYDDY, GELHY
   Description: Nio is outperforming competitors in China's brutal EV price war, posting 62% delivery growth in May ...

11. Elon Musk Just Linked SpaceX, xAI, Tesla, and Nvidia Into 1 Trade. Here's How to Position Your Portfolio.
   Published: 2026-05-23T18:14:00Z
   Tickers: TSLA, NVDA
   Description: The article analyzes how Elon Musk's companies—SpaceX, xAI, Tesla, and Nvidia—form an integrated AI ...

12. At a $1.2 Trillion Market Cap, Is Tesla Stock Overvalued or Undervalued Right Now?
   Published: 2026-06-08T16:15:00Z
   Tickers: TSLA
   Description: Tesla trades at an extremely high valuation with a P/E ratio of 357 and a forward P/E of 114x based ...

13. Is Tesla Stock Your Ticket to Becoming a Millionaire?
   Published: 2026-05-31T08:34:00Z
   Tickers: TSLA
   Description: While Tesla's stock has delivered exceptional historical returns (22,250% over 15 years), the articl...

14. Auditoria.AI introduces Governed Autonomy for Enterprise Office of the CFO at 2026 Gartner CFO Symposium
   Published: 2026-05-26T12:00:00Z
   Tickers: WDAY, ORCL, ORCLpD, SAP, NOW, MSFT
   Description: Auditoria.AI unveiled Governed Autonomy, a new operating framework that enables autonomous AI agents...

15. Softbank's Masayoshi Son Isn't Worried About An AI Bubble— He's Hunting For The Next Trillion-Dollar Industry: 'Just The Beginning'
   Published: 2026-06-02T08:46:39Z
   Tickers: SFTBY, ABBNY, META, GS, GSpA, GSpC, GSpD, AMJB, JPM, JPMpC, JPMpD, JPMpJ, JPMpK, JPMpL, JPMpM, VYLD, MS, MSpA, MSpE, MSpF, MSpI, MSpK, MSpL, MSpO, MSpP, MSpQ
   Description: SoftBank CEO Masayoshi Son believes the AI revolution is '50x bigger' than the dot-com boom and will...

16. Where Will Tesla Stock Be in 3 Years?
   Published: 2026-06-05T03:22:00Z
   Tickers: TSLA
   Description: Tesla's business is stabilizing with recovered profit margins and strong Chinese sales growth, while...

17. China's Puncture Robotics Firm True Health Files For Hong Kong IPO
   Published: 2026-06-05T12:55:58Z
   Tickers: ISRG
   Description: Guangdong true Health Medical Technology, a Chinese medical robotics company specializing in punctur...

18. Nio Is Zigging While Rivals Zag, and Shockingly It's Winning
   Published: 2026-06-06T07:05:00Z
   Tickers: NIO, BYDDY, GELHY
   Description: While Chinese automakers like BYD and Geely are rushing to export vehicles overseas to offset declin...

19. Nebius Launches AI Robotics Living Lab With NVIDIA Robotics Program
   Published: 2026-06-09T13:30:40Z
   Tickers: NBIS, NVDA
   Description: Nebius Group has launched a Physical AI Living Lab in partnership with NVIDIA to support British and...

20. Tesla vs. Alphabet: Who Wins the Autonomous AI Race?
   Published: 2026-05-27T12:07:00Z
   Tickers: TSLA, GOOG, GOOGL
   Description: Tesla and Alphabet are competing in the robotaxi market, which could be worth $5-10 trillion globall...

21. Tesla Investors Beware? SpaceX IPO Could Pull Cash, Attention And Musk Away From EV Giant
   Published: 2026-05-22T05:39:55Z
   Tickers: TSLA
   Description: SpaceX's upcoming IPO could negatively impact Tesla as it may divert investor attention, capital, an...

22. Tesla Just Lost One of Its Biggest Bears, but Is the Stock a Buy?
   Published: 2026-06-09T13:35:00Z
   Tickers: TSLA, AMJB, JPM, JPMpC, JPMpD, JPMpJ, JPMpK, JPMpL, JPMpM, VYLD
   Description: J.P. Morgan upgraded Tesla from underweight to neutral with a price target increase from $145 to $47...

23. 2 EV Stocks That Could Win Big Targeting the $10 Trillion Global Robotaxi Market
   Published: 2026-05-28T14:32:00Z
   Tickers: TSLA, RIVN, UBER
   Description: Electric vehicle stocks are positioned to benefit significantly from the emerging robotaxi market, e...

24. SpaceX-Tesla Merger Speculation: Is SPCX S-1 Setting The Stage?
   Published: 2026-05-21T15:31:50Z
   Tickers: TSLA, INTC
   Description: SpaceX filed its S-1 for a June 2026 IPO under ticker SPCX, fueling speculation about a potential me...

25. Tesla Stock Wobbles As Elon Musk Lines Up The SpaceX IPO
   Published: 2026-06-09T15:49:10Z
   Tickers: TSLA
   Description: Tesla shares declined 3.71% as SpaceX prepares for its Nasdaq debut on Friday with a $1.75 trillion ...

# 2) TEST: Checking Yahoo Finance API endpoints

In [17]:
# https://github.com/ranaroussi/yfinance
# https://algotrading101.com/learn/yfinance-guide/

import yfinance as yf
ticker="TSLA"
ticker_obj = yf.Ticker(ticker)

In [18]:
# daily stats for a stock: Open, High, Low, Close, Volume
historical_prices = ticker_obj.history(period="2y", interval="1d")

# show only date part in the index
historical_prices.index = historical_prices.index.date

historical_prices.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
2024-06-13,188.389999,191.080002,181.229996,182.470001,118984100,0.0,0.0
2024-06-14,185.800003,186.000000,176.919998,178.009995,82038200,0.0,0.0
2024-06-17,177.919998,188.809998,177.000000,187.440002,109786100,0.0,0.0
2024-06-18,186.559998,187.199997,182.369995,184.860001,68982300,0.0,0.0
2024-06-20,184.679993,185.210007,179.660004,181.570007,55893100,0.0,0.0

In [19]:
# Analyst price targets
ticker_obj.get_analyst_price_targets()

{'current': 406.43,
 'high': 600.0,
 'low': 123.0,
 'mean': 420.54633,
 'median': 460.0}

In [20]:
# Dividends or Stock splits history
ticker_obj.actions

                           Dividends  Stock Splits
Date
2020-08-31 00:00:00-04:00        0.0           5.0
2022-08-25 00:00:00-04:00        0.0           3.0

In [21]:
# Next earnings date + targets on EPS (Earnings)/revenue
ticker_obj.calendar

{'Earnings Date': [datetime.date(2026, 7, 22)],
 'Earnings High': 0.59,
 'Earnings Low': 0.26483,
 'Earnings Average': 0.45414,
 'Revenue High': 26059000000,
 'Revenue Low': 22800000000,
 'Revenue Average': 24634836150}

In [22]:
# FIN STATEMENTS -- too much of info, not needed for now
# ticker_obj.get_balancesheet()
# ticker_obj.get_cash_flow()
# ticker_obj.get_income_stmt()
# same as income stmt: ticker_obj.get_financials()

In [23]:
# EPS estimates vs. numberOfAnalysts
ticker_obj.get_earnings_estimate()

            avg      low  high  yearAgoEps  numberOfAnalysts  growth
period
0q      0.45414  0.26483  0.59     0.40000                25  0.1353
+1q     0.53750  0.29981  0.83     0.50000                25  0.0750
0y      2.05937  1.35491  3.19     1.66000                34  0.2406
+1y     2.49995  1.46400  3.65     2.05937                30  0.2139

In [24]:
# How analysts have revised their EPS estimates over time?
ticker_obj.get_eps_revisions()

        upLast7days  upLast30days  downLast30days  downLast7Days
period
0q                1             2               1              0
+1q               1             1               1              0
0y                1             1               2              0
+1y               0             0               3              1

In [25]:
# This section retrieves consensus analyst growth expectations from Yahoo Finance for the selected ticker. 
# The values represent estimated earnings growth and are expressed in decimal form, 
# where positive values indicate expected growth and negative values indicate contraction. 
# Estimates are provided across multiple time horizons: 0q refers to the current fiscal quarter, 
# +1q to the next fiscal quarter, 0y to the current fiscal year, and +1y to the next fiscal year.
#  Short-term quarterly estimates tend to be more volatile, while annual estimates provide a broader view of expected performance.

ticker_obj.get_growth_estimates()

        stockTrend  indexTrend
period
0q          0.1353      0.2598
+1q         0.0750      0.2028
0y          0.2406      0.2308
+1y         0.2139      0.1704
LTG            NaN      0.1220

In [26]:
ticker_obj.get_earnings_history()

            epsActual  epsEstimate  epsDifference  surprisePercent
quarter
2025-06-30       0.40      0.40391         -0.004          -0.0097
2025-09-30       0.50      0.55885         -0.060          -0.1053
2025-12-31       0.50      0.45061          0.050           0.1096
2026-03-31       0.41      0.34999          0.060           0.1715

In [27]:
import pandas as pd
news = pd.DataFrame(ticker_obj.get_news())
news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       10 non-null     object
 1   content  10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [28]:
news

,id,content
0,8ef49b96-5099-399d-b765-1e95749d4f6f,"{'id': '8ef49b96-5099-399d-b765-1e95749d4f6f',..."
1,eafe3e98-b47c-3e2a-9345-a01348e43c03,"{'id': 'eafe3e98-b47c-3e2a-9345-a01348e43c03',..."
2,3cdded0e-83d4-37e2-bafa-229d9c2a642f,"{'id': '3cdded0e-83d4-37e2-bafa-229d9c2a642f',..."
3,846e88d0-53ac-3b91-8527-c9c805463568,"{'id': '846e88d0-53ac-3b91-8527-c9c805463568',..."
4,0679fbd1-f17d-3a74-8d34-f094d76bae10,"{'id': '0679fbd1-f17d-3a74-8d34-f094d76bae10',..."
5,6c53b91b-d39c-3259-8e3d-184a3c3652a8,"{'id': '6c53b91b-d39c-3259-8e3d-184a3c3652a8',..."
6,d06aeb26-91e1-3940-8138-aa75d4ef3209,"{'id': 'd06aeb26-91e1-3940-8138-aa75d4ef3209',..."
7,2729cce8-9d0e-39e4-8664-4ebbc474140b,"{'id': '2729cce8-9d0e-39e4-8664-4ebbc474140b',..."
8,e54dbe29-f9ed-3af4-846a-3e1c4d735f61,"{'id': 'e54dbe29-f9ed-3af4-846a-3e1c4d735f61',..."
9,a687efe7-066a-3e64-91b2-1124f52354d0,"{'id': 'a687efe7-066a-3e64-91b2-1124f52354d0',..."

In [29]:
import pandas as pd

# Create a new DataFrame from the 'content' column of the 'news' DataFrame
news_df = pd.DataFrame(news['content'].tolist())

# Display the first few rows of the new DataFrame
display(news_df.head())

,id,contentType,title,description,summary,pubDate,displayTime,isHosted,bypassModal,previewUrl,thumbnail,provider,canonicalUrl,clickThroughUrl,metadata,finance,storyline
0,8ef49b96-5099-399d-b765-1e95749d4f6f,STORY,OpenAI Just Launched a Robotics Division. Shou...,,ChatGPT's parent isn't an immediate threat. Th...,2026-06-14T12:05:00Z,2026-06-14T12:05:00Z,True,False,None,{'originalUrl': 'https://media.zenfs.com/en/mo...,"{'displayName': 'Motley Fool', 'url': 'http://...",{'url': 'https://www.fool.com/investing/2026/0...,{'url': 'https://finance.yahoo.com/sectors/tec...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None
1,eafe3e98-b47c-3e2a-9345-a01348e43c03,STORY,3 Genius Stocks I'm Buying Instead of the Spac...,,"SpaceX IPO may be popular, but there are bette...",2026-06-14T08:05:00Z,2026-06-14T08:05:00Z,True,False,None,{'originalUrl': 'https://media.zenfs.com/en/mo...,"{'displayName': 'Motley Fool', 'url': 'http://...",{'url': 'https://www.fool.com/investing/2026/0...,{'url': 'https://finance.yahoo.com/markets/sto...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None
2,3cdded0e-83d4-37e2-bafa-229d9c2a642f,STORY,SpaceX Surge Further Boosts Saudi Billionaire ...,,(Bloomberg) -- Friday’s debut share surge for ...,2026-06-14T07:33:34Z,2026-06-14T07:33:34Z,True,False,None,None,"{'displayName': 'Bloomberg', 'url': 'https://w...",{'url': 'https://finance.yahoo.com/markets/sto...,{'url': 'https://finance.yahoo.com/markets/sto...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None
3,846e88d0-53ac-3b91-8527-c9c805463568,STORY,Can Rivian Beat Tesla in the Long Term?,,Rivian began delivering its affordable R2 flee...,2026-06-14T02:53:00Z,2026-06-14T02:53:00Z,True,False,None,{'originalUrl': 'https://media.zenfs.com/en/mo...,"{'displayName': 'Motley Fool', 'url': 'http://...",{'url': 'https://www.fool.com/investing/2026/0...,{'url': 'https://finance.yahoo.com/markets/sto...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None
4,0679fbd1-f17d-3a74-8d34-f094d76bae10,STORY,Elon Musk Is Now the World's First Trillionair...,,A second Musk-led megacap is now publicly trad...,2026-06-14T01:31:00Z,2026-06-14T01:31:00Z,True,False,None,{'originalUrl': 'https://media.zenfs.com/en/mo...,"{'displayName': 'Motley Fool', 'url': 'http://...",{'url': 'https://www.fool.com/investing/2026/0...,{'url': 'https://finance.yahoo.com/markets/sto...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None

In [30]:
# summary of news articles for the ticker (Yahoo Finance)
from pprint import pprint 
for e in news_df.summary:
    pprint(e)
    print('-----')

("ChatGPT's parent isn't an immediate threat. The fact that it's planning on "
 "entering the market at all, however, underscores the idea that Tesla isn't "
 'going to be in this business all by itself.')
-----
'SpaceX IPO may be popular, but there are better options available.'
-----
('(Bloomberg) -- Friday’s debut share surge for SpaceX is bolstering the '
 'fortunes of one of Saudi Arabia’s richest men. Most Read from BloombergWhy '
 'Musk Raced to Take SpaceX Public in the World’s Biggest IPOTrump Eyes Sunday '
 'Iran Deal But Tehran Says Still Reviewing TextAnthropic Shuts Down Mythos '
 'Access After Sweeping US OrderUS Wants to Avoid Congressional Vote on Trade '
 'Deal, Carney SaysAir India Plans to Downsize With Owner Tata Balking at '
 'LossesPrince Alwaleed bin Talal’s investment firm Kingd')
-----
('Rivian began delivering its affordable R2 fleet this week in a push to bring '
 'the company to the mainstream.')
-----
('A second Musk-led megacap is now publicly traded -- and that quietly changes '
 "a few things for the electric-car maker's investors.")
-----
('Venture capitalist Steve Westly says SpaceX is "three moonshots in one '
 'company" and the math only works if most of them pay off. On June 12, SpaceX '
 '(SPCX) just pulled off the biggest initial public offering in stock market '
 'history. The company raised $75 billion, priced shares at $135 each, ...')
-----
("Cathie Wood's firm ARK Invest staked a large position in Elon Musk's SpaceX "
 'on Friday. The firm already has a huge chunk of Tesla stock.')
-----
('FTSE Russell confirmed SpaceX will join the Russell 1000 and Russell Top 200 '
 'on June 26, with MSCI adding it to its standard and large-cap indexes on '
 'June 29.')
-----
('The upcoming SpaceX IPO, which is scheduled to kick off on Friday, June 12, '
 'could result in Tesla Inc. investors exiting their positions in the EV '
 'giant, according to investor Gary Black of The Future Fund LLC. Investors To '
 '‘Lighten’...')
-----
("ArcBest's ABF Freight unit is expanding its electric trucking program with "
 'new Tesla Semi trucks beyond its initial California and Nevada pilot route. '
 'This move shifts the Tesla Semi use from a limited trial to broader '
 "deployment across more of ArcBest's network. Early feedback points to a "
 'positive driver experience and solid operational performance for the '
 'electric trucks. For investors following NasdaqGS:ARCB, this development '
 'adds another piece to the story around how the company is...')
-----

In [31]:
# Fast info about the stock
ticker_obj.get_fast_info().items()

[('currency', 'USD'),
 ('dayHigh', 406.67999267578125),
 ('dayLow', 386.760009765625),
 ('exchange', 'NMS'),
 ('fiftyDayAverage', 398.3000012207031),
 ('lastPrice', 406.42999267578125),
 ('lastVolume', 63514500),
 ('marketCap', 1526438825382.7869),
 ('open', 399.489990234375),
 ('previousClose', 398.9999),
 ('quoteType', 'EQUITY'),
 ('regularMarketPreviousClose', 399.1499938964844),
 ('shares', 3755723871),
 ('tenDayAverageVolume', 49458150),
 ('threeMonthAverageVolume', 58958131),
 ('timezone', 'America/New_York'),
 ('twoHundredDayAverage', 415.6944003295898),
 ('yearChange', 0.23486156426391933),
 ('yearHigh', 498.8299865722656),
 ('yearLow', 288.7699890136719)]

In [32]:
import json

In [33]:
# a lot of info - potentially useful fields:
# website, industry, sector, fullTimeEmployees, companyOfficers, previousClose, open, dayLow, dayHigh, 
# beta, forwardPE, trailingPE, volume, averageVolume, averageVolume10days, marketCap, fiftyTwoWeekLow, 
# fiftyTwoWeekHigh, allTimeHigh, allTimeLow, priceToSalesTrailing12Months, fiftyDayAverage, twoHundredDayAverage
# profitMargins, sharesPercentSharesOut, heldPercentInsiders, heldPercentInstitutions, shortRatio, bookValue, priceToBook
# earningsQuarterlyGrowth, trailingEps, forwardEps, 52WeekChange, currentPrice,
#   targetHighPrice, targetLowPrice, targetMeanPrice, targetMedianPrice, recommendationMean,
# recommendationKey, numberOfAnalystOpinions, totalCashPerShare,totalCashPerShare, returnOnAssets, returnOnEquity,
# earningsGrowth, revenueGrowth, grossMargins, ebitdaMargins, operatingMargins, region, fullExchangeName, regularMarketDayRange, fiftyTwoWeekRange,
# fiftyTwoWeekHighChange, cryptoTradeable, displayName, trailingPegRatio
info = ticker_obj.get_info()
print(json.dumps(info, indent=2, default=str))

{
  "address1": "1 Tesla Road",
  "city": "Austin",
  "state": "TX",
  "zip": "78725",
  "country": "United States",
  "phone": "512 516 8177",
  "website": "https://www.tesla.com",
  "industry": "Auto Manufacturers",
  "industryKey": "auto-manufacturers",
  "industryDisp": "Auto Manufacturers",
  "sector": "Consumer Cyclical",
  "sectorKey": "consumer-cyclical",
  "sectorDisp": "Consumer Cyclical",
  "longBusinessSummary": "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally. The company operates in two segments, Automotive; and Energy Generation and Storage. The company offers electric vehicles, as well as sells automotive regulatory credits; and non-warranty maintenance services and collision, automotive insurance services, as well as part sales and retail merchandise sale. It also provides sedans and sport utility vehicles through direct and used vehicle sales, a network of Tesla Superchargers, and in-app upgrades; purchase financing and leasing services; services for electric vehicles through its company-owned service locations and Tesla mobile service technicians; and vehicle limited warranties and extended service plans. In addition, the company engages in the design, manufacture, installation, sale, and leasing of solar energy generation and energy storage products, and related services to residential, commercial, and industrial customers and utilities through its website, stores, and galleries, as well as through a network of channel partners. Further, it provides services and repairs to its energy product customers, including under warranty and extended service plans; and various financing options to its residential customers; lithium-ion battery energy storage products, such as Powerwall and Megapack; energy generation products, including solar panels and solar roof; self-driving development and artificial intelligence software, vehicle control and infotainment software, and battery and powertrain. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was incorporated in 2003 and is headquartered in Austin, Texas.",
  "fullTimeEmployees": 134785,
  "companyOfficers": [
    {
      "maxAge": 1,
      "name": "Mr. Elon R. Musk",
      "age": 54,
      "title": "Co-Founder, Technoking of Tesla, CEO & Director",
      "yearBorn": 1971,
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 129602732032
    },
    {
      "maxAge": 1,
      "name": "Mr. Vaibhav  Taneja",
      "age": 47,
      "title": "Chief Financial Officer",
      "yearBorn": 1978,
      "fiscalYear": 2025,
      "totalPay": 403000,
      "exercisedValue": 15033838,
      "unexercisedValue": 417696224
    },
    {
      "maxAge": 1,
      "name": "Mr. Xiaotong  Zhu",
      "age": 45,
      "title": "Senior Vice President of APAC & Global Vehicle Manufacturing",
      "yearBorn": 1980,
      "fiscalYear": 2025,
      "totalPay": 376322,
      "exercisedValue": 4548562,
      "unexercisedValue": 808327104
    },
    {
      "maxAge": 1,
      "name": "Travis  Axelrod",
      "title": "Head of Investor Relations",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. Brandon  Ehrhart",
      "title": "General Counsel & Corporate Secretary",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. Franz  von Holzhausen",
      "title": "Chief Designer",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Ms. Roxanne  Inskip-Kaye",
      "title": "Head of Operations - Electric Vehicle Business",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. John  Walker",
      "age": 62,
      "title": "Vice President of Sales - North America",
      "yearBorn": 1963,
      "fiscalYear": 2025,
      "totalPay": 121550,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. Rodney D. Westmoreland Jr.",
      "title": "Director of Construction Management",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. Lars  Moravy",
      "title": "Vice President of Vehicle Engineering",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    }
  ],
  "auditRisk": 4,
  "boardRisk": 10,
  "compensationRisk": 10,
  "shareHolderRightsRisk": 9,
  "overallRisk": 10,
  "governanceEpochDate": 1780531200,
  "compensationAsOfEpochDate": 1767139200,
  "executiveTeam": [],
  "maxAge": 86400,
  "priceHint": 2,
  "previousClose": 399.15,
  "open": 399.46,
  "dayLow": 386.76,
  "dayHigh": 406.68,
  "regularMarketPreviousClose": 399.15,
  "regularMarketOpen": 399.46,
  "regularMarketDayLow": 386.76,
  "regularMarketDayHigh": 406.68,
  "payoutRatio": 0.0,
  "beta": 1.798,
  "trailingPE": 369.4818,
  "forwardPE": 162.57526,
  "volume": 62460127,
  "regularMarketVolume": 63652286,
  "averageVolume": 58965338,
  "averageVolume10days": 49458150,
  "averageDailyVolume10Day": 49458150,
  "bid": 403.31,
  "ask": 405.65,
  "bidSize": 4,
  "askSize": 3,
  "marketCap": 1526438821888,
  "nonDilutedMarketCap": 1526438852890,
  "fiftyTwoWeekLow": 288.77,
  "fiftyTwoWeekHigh": 498.83,
  "allTimeHigh": 498.83,
  "allTimeLow": 0.998667,
  "priceToSalesTrailing12Months": 15.595161,
  "fiftyDayAverage": 398.3,
  "twoHundredDayAverage": 415.6944,
  "trailingAnnualDividendRate": 0.0,
  "trailingAnnualDividendYield": 0.0,
  "currency": "USD",
  "tradeable": false,
  "enterpriseValue": 1498271842304,
  "profitMargins": 0.03946,
  "floatShares": 2815891530,
  "sharesOutstanding": 3755723871,
  "sharesShort": 76947758,
  "sharesShortPriorMonth": 76673071,
  "sharesShortPreviousMonthDate": 1777507200,
  "dateShortInterest": 1780012800,
  "sharesPercentSharesOut": 0.020499999,
  "heldPercentInsiders": 0.11111,
  "heldPercentInstitutions": 0.44926,
  "shortRatio": 1.48,
  "shortPercentOfFloat": 0.023,
  "impliedSharesOutstanding": 3755723871,
  "bookValue": 21.897,
  "priceToBook": 18.56099,
  "lastFiscalYearEnd": 1767139200,
  "nextFiscalYearEnd": 1798675200,
  "mostRecentQuarter": 1774915200,
  "earningsQuarterlyGrowth": 0.166,
  "netIncomeToCommon": 3862000128,
  "trailingEps": 1.1,
  "forwardEps": 2.49995,
  "pegRatio": 5.6,
  "lastSplitFactor": "3:1",
  "lastSplitDate": 1661385600,
  "enterpriseToRevenue": 15.307,
  "enterpriseToEbitda": 135.052,
  "52WeekChange": 0.23486161,
  "SandP52WeekChange": 0.23177934,
  "quoteType": "EQUITY",
  "currentPrice": 406.43,
  "targetHighPrice": 600.0,
  "targetLowPrice": 123.0,
  "targetMeanPrice": 420.54633,
  "targetMedianPrice": 460.0,
  "recommendationMean": 2.34043,
  "recommendationKey": "buy",
  "numberOfAnalystOpinions": 41,
  "totalCash": 44743000064,
  "totalCashPerShare": 11.913,
  "ebitda": 11093999616,
  "totalDebt": 15889999872,
  "quickRatio": 1.43,
  "currentRatio": 2.043,
  "totalRevenue": 97878999040,
  "debtToEquity": 18.738,
  "revenuePerShare": 30.312,
  "returnOnAssets": 0.022330001,
  "returnOnEquity": 0.04901,
  "grossProfits": 18660999168,
  "freeCashflow": 5251999744,
  "operatingCashflow": 16528000000,
  "earningsGrowth": 0.083,
  "revenueGrowth": 0.158,
  "grossMargins": 0.19065,
  "ebitdaMargins": 0.11334,
  "operatingMargins": 0.04203,
  "financialCurrency": "USD",
  "symbol": "TSLA",
  "language": "en-US",
  "region": "US",
  "typeDisp": "Equity",
  "quoteSourceName": "Nasdaq Real Time Price",
  "triggerable": true,
  "customPriceAlertConfidence": "HIGH",
  "averageDailyVolume3Month": 58965338,
  "fiftyTwoWeekLowChange": 117.66,
  "fiftyTwoWeekLowChangePercent": 0.40745232,
  "fiftyTwoWeekRange": "288.77 - 498.83",
  "fiftyTwoWeekHighChange": -92.399994,
  "fiftyTwoWeekHighChangePercent": -0.18523344,
  "fiftyTwoWeekChangePercent": 23.48616,
  "earningsTimestamp": 1776888000,
  "earningsTimestampStart": 1784750400,
  "earningsTimestampEnd": 1784750400,
  "earningsCallTimestampStart": 1776893400,
  "earningsCallTimestampEnd": 1776893400,
  "isEarningsDateEstimate": true,
  "epsTrailingTwelveMonths": 1.1,
  "epsForward": 2.49995,
  "epsCurrentYear": 2.05937,
  "priceEpsCurrentYear": 197.35646,
  "fiftyDayAverageChange": 8.130005,
  "fiftyDayAverageChangePercent": 0.020411763,
  "twoHundredDayAverageChange": -9.264404,
  "twoHundredDayAverageChangePercent": -0.022286575,
  "sourceInterval": 15,
  "exchangeDataDelayedBy": 0,
  "averageAnalystRating": "2.3 - Buy",
  "cryptoTradeable": false,
  "shortName": "Tesla, Inc.",
  "longName": "Tesla, Inc.",
  "corporateActions": [],
  "postMarketTime": 1781308797,
  "regularMarketTime": 1781294400,
  "exchange": "NMS",
  "messageBoardId": "finmb_27444752",
  "exchangeTimezoneName": "America/New_York",
  "exchangeTimezoneShortName": "EDT",
  "gmtOffSetMilliseconds": -14400000,
  "market": "us_market",
  "esgPopulated": false,
  "regularMarketChangePercent": 1.8238755,
  "regularMarketPrice": 406.43,
  "hasPrePostMarketData": true,
  "firstTradeDateMilliseconds": 1277818200000,
  "postMarketChangePercent": -0.08119149,
  "postMarketPrice": 406.1,
  "postMarketChange": -0.32998657,
  "regularMarketChange": 7.279999,
  "regularMarketDayRange": "386.76 - 406.68",
  "fullExchangeName": "NasdaqGS",
  "marketState": "CLOSED",
  "displayName": "Tesla",
  "trailingPegRatio": 5.5963
}

In [34]:
# more history metadata - not sure we need this now
import json

metadata = ticker_obj.get_history_metadata()
print(json.dumps(metadata, indent=2, default=str))

{
  "currency": "USD",
  "symbol": "TSLA",
  "exchangeName": "NMS",
  "fullExchangeName": "NasdaqGS",
  "instrumentType": "EQUITY",
  "firstTradeDate": 1277818200,
  "regularMarketTime": 1781294400,
  "hasPrePostMarketData": true,
  "gmtoffset": -14400,
  "timezone": "EDT",
  "exchangeTimezoneName": "America/New_York",
  "regularMarketPrice": 406.43,
  "fiftyTwoWeekHigh": 498.83,
  "fiftyTwoWeekLow": 288.77,
  "regularMarketDayHigh": 406.68,
  "regularMarketDayLow": 386.76,
  "regularMarketVolume": 63652286,
  "longName": "Tesla, Inc.",
  "shortName": "Tesla, Inc.",
  "chartPreviousClose": 391.0,
  "previousClose": 399.15,
  "scale": 3,
  "priceHint": 2,
  "currentTradingPeriod": {
    "pre": {
      "timezone": "EDT",
      "start": 1781251200,
      "end": 1781271000,
      "gmtoffset": -14400
    },
    "regular": {
      "timezone": "EDT",
      "start": 1781271000,
      "end": 1781294400,
      "gmtoffset": -14400
    },
    "post": {
      "timezone": "EDT",
      "start": 1781294400,
      "end": 1781308800,
      "gmtoffset": -14400
    }
  },
  "tradingPeriods": {
    "pre": [
      [
        {
          "timezone": "EDT",
          "start": 1780905600,
          "end": 1780925400,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780992000,
          "end": 1781011800,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781078400,
          "end": 1781098200,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781164800,
          "end": 1781184600,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781251200,
          "end": 1781271000,
          "gmtoffset": -14400
        }
      ]
    ],
    "post": [
      [
        {
          "timezone": "EDT",
          "start": 1780948800,
          "end": 1780963200,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781035200,
          "end": 1781049600,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781121600,
          "end": 1781136000,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781208000,
          "end": 1781222400,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781294400,
          "end": 1781308800,
          "gmtoffset": -14400
        }
      ]
    ],
    "regular": [
      [
        {
          "timezone": "EDT",
          "start": 1780925400,
          "end": 1780948800,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781011800,
          "end": 1781035200,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781098200,
          "end": 1781121600,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781184600,
          "end": 1781208000,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1781271000,
          "end": 1781294400,
          "gmtoffset": -14400
        }
      ]
    ]
  },
  "dataGranularity": "1h",
  "range": "5d",
  "validRanges": [
    "1d",
    "5d",
    "1mo",
    "3mo",
    "6mo",
    "1y",
    "2y",
    "5y",
    "10y",
    "ytd",
    "max"
  ],
  "lastTrade": {
    "Price": 406.1,
    "Time": "2026-06-12 19:59:57-04:00"
  }
}

## 3) TEST Social posts from X/Reddit
 * https://docs.x.ai/developers/tools/x-search
 * https://docs.x.ai/developers/tools/citations
 * IMPORTANT! We're using the OpenAI's compatible function call (Responses API) rather than what you can read on the x-search page

In [35]:
import openai

In [36]:
def get_recent_social_posts(ticker: str, max_posts: int = 5, days_back: int = 1):
    """
    Enhanced version with more x_search parameters.
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found',
            'posts': []
        }
    
    try:
        from datetime import datetime, timedelta
        
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        # Calculate date range
        to_date = datetime.now()
        from_date = to_date - timedelta(days=days_back)
        
        # Enhanced search query
        search_query = f"""
        Search X/Twitter for recent posts about ${ticker} stock.
        
        Requirements:
        - Find {max_posts} posts from the last {days_back} day(s)
        - Sort by most recent timestamp first
        - Include exact post times (e.g., "2 hours ago", "45 minutes ago")
        - Provide real, working X.com links
        - Include post content, author handles, engagement metrics
        - Analyze sentiment (bullish/bearish/neutral)
        
        Focus on posts about:
        - Stock price movements
        - Company news reactions
        - Earnings discussions
        - Technical analysis
        - Market sentiment
        
        Date range: {from_date.strftime('%Y-%m-%d')} to {to_date.strftime('%Y-%m-%d')}
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=search_query,
            tools=[{"type": "x_search"}]
        )
        
        # Extract response content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'search_params': {
                'max_posts': max_posts,
                'days_back': days_back,
                'date_range': f"{from_date.strftime('%Y-%m-%d')} to {to_date.strftime('%Y-%m-%d')}"
            },
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'api_used': 'responses_api_with_x_search'
        }
        
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'Error: {str(e)}',
            'posts': []
        }

In [37]:
# We'll test the news retrieval and search functionality with a specific ticker and a limit on the number of posts to retrieve.
max_posts = 10
ticker = 'TSLA'

# Test it
print("Testing X.AI ...")
result = get_recent_social_posts(ticker, max_posts)
if 'error' in result:
    print(f"❌ {result['error']}")
else:
    print(f"✅ Got response for {result['ticker']}")

Testing X.AI ...
✅ Got response for TSLA

In [38]:
print(result['response'])

**Here are 10 of the most recent X posts about $TSLA** (from June 13, 2026, sorted by most recent timestamp first). These focus on stock price action, technical analysis, market sentiment, and related news. All links are real/working X.com URLs based on the post IDs returned.

1. **@OGemHODL** (23:58:51 GMT, ~20–30 min ago)
   Content: "TESLA IS CHARGING UP! MATURING BULL STRUCTURE ON TSLA 🚗⚡ SIGNAL DETAILS: $TSLA /USDT Direction: LONG 🟢 ... Target 1: 419.44 ... Stop Loss: 385.00" (with chart)
   Engagement: 0 likes, 1 repost, 0 quotes, 0 replies, 44 views
   Sentiment: **Bullish** (long setup with high profit targets).
   Link: https://x.com/OGemHODL/status/2065947037057888705

2. **@Robert46989257** (23:58:10 GMT)
   Content: "lÄnD oF frEE speeecH so they 'asked' twitter to get his adress ? thats pure Gestapo stuff... $TSLA $NVDA $NOW $PLTR" (replying to ICE/FBI post)
   Engagement: 0 likes, 0 reposts, 0 quotes, 0 replies, 159 views
   Sentiment: **Neutral** (mentions $TSLA in passing amid free-speech discussion).
   Link: https://x.com/Robert46989257/status/2065946862180319255

3. **@frcryptonewsfr** (23:58:05 GMT)
   Content: "They often say that to build the future, you need a dose of madness. Look at Elon Musk... $TSLA... Investing in $PLTR isn't just buying a tech stock; it's betting on that rare blend..."
   Engagement: 2 likes, 0 reposts, 0 quotes, 0 replies, 77 views
   Sentiment: **Bullish** (positive on Musk/TSLA vision).
   Link: https://x.com/frcryptonewsfr/status/2065946845197599159

4. **@BruceKnuteson** (23:57:34 GMT)
   Content: "Much of Elon’s fortune actually does seem to have emerged from pure market magic: the only plausible explanation for this strikingly suspicious return pattern in $TSLA is the market manipulation described in [paper]" (with chart)
   Engagement: 0 likes, 0 reposts, 0 quotes, 1 reply, 32 views
   Sentiment: **Bearish** (accuses market manipulation in TSLA).
   Link: https://x.com/BruceKnuteson/status/2065946712372367377

5. **@Hugoilcapitano** (23:52:42 GMT)
   Content: "Y algunos dirán: $TSLA tiene futuro, $ADBE no. Por acá, con posición en la 2da. Creo que aún tiene algo para dar..."
   Engagement: 0 likes, 0 reposts, 0 quotes, 0 replies, 154 views
   Sentiment: **Neutral/Bullish** (prefers ADBE but acknowledges TSLA future).
   Link: https://x.com/Hugoilcapitano/status/2065945490261229569

6. **@gizemcokdar** (23:50:22 GMT)
   Content: "Started my weekend trading with $TSLA 📊🚀 #Bitget" (with screenshot)
   Engagement: 1 like, 0 reposts, 0 quotes, 0 replies, 1 view
   Sentiment: **Bullish** (positive weekend trade).
   Link: https://x.com/gizemcokdar/status/2065944900009447571

7. **@rdd147** (23:47:03 GMT)
   Content: "Musk sets the stage to announce Neuralink IPO $SPCX $TSLA" (replying to Neuralink "God-like powers" post)
   Engagement: 9 likes, 2 reposts, 0 quotes, 4 replies, 745 views
   Sentiment: **Bullish** (positive on Musk/TSLA ecosystem).
   Link: https://x.com/rdd147/status/2065944065439662281

8. **@DrAntonEremin** (23:47:20 GMT)
   Content: "#xauusd #gold #crypto The market never sleeps... $TSLA $ZBCN" (with chart)
   Engagement: 0 likes, 0 reposts, 0 quotes, 0 replies, 61 views
   Sentiment: **Neutral** (mentions $TSLA in trading promo).
   Link: https://x.com/DrAntonEremin/status/2065944136499237310

9. **@TrendsDotGlobal** (23:41:51 GMT)
   Content: "JUST IN: $TSLA ⚡️ Construction work on the Optimus factory near Tesla’s Gigafactory Texas... @Tesla says the site will support production of future versions of its humanoid robot..." (with photo)
   Engagement: 3 likes, 0 reposts, 0 quotes, 0 replies, 127 views
   Sentiment: **Bullish** (positive on robotics/expansion news).
   Link: https://x.com/TrendsDotGlobal/status/2065942757643055559

10. **@Ledora037** (16:13:13 GMT)
    Content: "$TSLA is sitting at a key decision zone... 446 remains the line for bulls... Structure vs narrative is the real trade right now." (with chart)
    Engagement: 20 likes, 2 reposts, 0 quotes, 5 replies, 277 views
    Sentiment: **Neutral/Bullish** (balanced TA with bullish long-term narrative).
    Link: https://x.com/Ledora037/status/2065829853904138262

**Overall sentiment summary** (across these posts): Mixed but leaning **slightly bullish** on long-term Musk/TSLA narrative and robotics, with some bearish technical warnings and skepticism about price action. Many posts highlight technical levels (e.g., 446 resistance, 403–406 entry zones) and ecosystem news (Optimus, Neuralink). No major earnings discussion in this exact window.

In [39]:
# Search with SORT

def get_recent_social_posts_with_xai(ticker: str, max_posts: int = 5, sort_by: str = "engagement"):
    """
    Get recent Twitter/X posts using xAI's Responses API with x_search tool.
    
    Args:
        ticker: Stock ticker symbol
        max_posts: Number of posts to return
        sort_by: "engagement" (views+likes+replies) or "recent" (timestamp)
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found. Set it in your .envrc file.',
            'posts': []
        }
    
    try:
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        # Build search query based on sorting preference
        if sort_by == "engagement":
            sort_instruction = """
            IMPORTANT: Sort by HIGHEST ENGAGEMENT (total impact) first.
            - Calculate engagement score = views + likes + replies + retweets
            - Show the posts with highest engagement numbers first
            - These are the most impactful/viral posts about the stock
            """
        else:
            sort_instruction = "Sort by most recent timestamp first."
        
        search_query = f"""
        Search X/Twitter for posts about ${ticker} stock from the last 24 hours.
        
        {sort_instruction}
        
        For each of the {max_posts} posts, provide:
        - Post content
        - Author username
        - Exact engagement metrics: views, likes, replies, retweets, bookmarks
        - Timestamp
        - Real working X.com link
        - Sentiment analysis
        
        Focus on posts with substantial engagement that show real market impact.
        Skip posts with 0 or minimal engagement unless specifically requested.
        
        Format each post clearly showing the engagement numbers prominently.
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=search_query,
            tools=[{"type": "x_search"}]
        )
        
        # Extract response content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'sort_by': sort_by,
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'api_used': 'responses_api_with_x_search'
        }
        
    except openai.AuthenticationError:
        return {
            'ticker': ticker,
            'error': 'Authentication failed. Check your XAI_API_KEY.',
            'posts': []
        }
    
    except openai.RateLimitError:
        return {
            'ticker': ticker,
            'error': 'Rate limit exceeded. Try again later.',
            'posts': []
        }
    
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'API error: {str(e)}',
            'posts': []
        }

# Function for high-engagement posts specifically
def get_viral_social_posts(ticker: str, max_posts: int = 5, min_engagement: int = 100):
    """
    Get posts with high engagement (viral posts) about a stock.
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found',
            'posts': []
        }
    
    try:
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        viral_search_query = f"""
        Search X/Twitter for HIGH-ENGAGEMENT posts about ${ticker} stock from the last 48 hours.
        
        CRITERIA:
        - Only show posts with {min_engagement}+ total engagement (views + likes + replies + retweets)
        - Sort by HIGHEST engagement first (most viral/impactful)
        - Focus on posts that are actually moving opinions or generating discussion
        - Skip spam, bot posts, or posts with minimal engagement
        
        Return the top {max_posts} most viral posts with:
        - Total engagement score prominently displayed
        - Post content 
        - Author (prioritize verified accounts, influencers, analysts)
        - All engagement metrics broken down
        - Working X.com links
        - Why this post is significant/viral
        
        These should be posts that are actually influencing ${ticker} sentiment in the market.
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=viral_search_query,
            tools=[{"type": "x_search"}]
        )
        
        # Extract content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'search_type': 'viral_posts',
            'min_engagement': min_engagement,
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'Error: {str(e)}',
            'posts': []
        }

In [40]:
print("=== Testing Engagement-Sorted Posts ===")
result1 = get_recent_social_posts_with_xai("TSLA", 5, sort_by="engagement")
if 'error' in result1:
    print(f"❌ Error: {result1['error']}")
else:
    print(f"✅ Success - sorted by {result1['sort_by']}")
    print("Top engagement posts:")

=== Testing Engagement-Sorted Posts ===
✅ Success - sorted by engagement
Top engagement posts:

In [41]:
print(result1['response'])

**Top 5 posts about $TSLA from the last 24 hours (sorted by highest engagement score = views + likes + replies + reposts):**

**1. Highest engagement**
**Author:** @Realcoinforge
**Content:** 🇺🇸 TESLA HAS JUST SHOWN A MASSIVE BULL SIGNAL BY BREAKING A TRENDLINE. Every time $TSLA broke a trendline on the higher time-frame, it led to a massive expansion. It has just happened again and if the pattern continues, we will see Tesla at $500 real soon. I believe the next 5 years will be game-changing. Tesla has huge plans for the future.
**Engagement:** Views: 13,784 | Likes: 116 | Replies: 5 | Reposts: 7 | Bookmarks: 13
**Timestamp:** Sat, 13 Jun 2026 17:00:16 GMT
**Link:** https://x.com/Realcoinforge/status/2065841698203422976
**Sentiment:** Strongly bullish (highlighting a technical breakout and long-term upside to $500+).

**2.**
**Author:** @peterli34923561
**Content:** $TSLA --- $TSLA has officially disclosed it holds approximately 19 million shares of SpaceX. Valued at $2.56 billion at the IPO price, this is a massive, previously underpriced hidden asset on Tesla’s balance sheet. With the merger of SpaceX and xAI... [full detailed bull thesis on AI, Energy, Robotics, FSD, Optimus, etc., with $600 price target mention].
**Engagement:** Views: 8,168 | Likes: 105 | Replies: 6 | Reposts: 9 | Bookmarks: 26
**Timestamp:** Sat, 13 Jun 2026 03:43:08 GMT
**Link:** https://x.com/peterli34923561/status/2065641088891924697
**Sentiment:** Strongly bullish (emphasizing undervalued assets and massive revaluation potential).

**3.**
**Author:** @BullTradeFinder
**Content:** $TSLA $400 holds you have some upside to $420-$430. OPEX so be careful, things can change quickly. (with chart)
**Engagement:** Views: 6,846 | Likes: 32 | Replies: 2 | Reposts: 0 | Bookmarks: 3
**Timestamp:** Sun, 14 Jun 2026 00:29:09 GMT
**Link:** https://x.com/BullTradeFinder/status/2065954661283062069
**Sentiment:** Bullish (short-term price target with caution on OPEX).

**4.**
**Author:** @SaralTrader
**Content:** $TSLA - Testing patience...Set up is intact, now at breakeven.! Holding Tesla is riding a rollercosater..! (with chart)
**Engagement:** Views: 4,934 | Likes: 36 | Replies: 1 | Reposts: 0 | Bookmarks: 3
**Timestamp:** Sat, 13 Jun 2026 16:27:24 GMT
**Link:** https://x.com/SaralTrader/status/2065833425093722485
**Sentiment:** Neutral-to-bullish (patient holding, setup intact despite volatility).

**5.**
**Author:** @RebellioMarket
**Content:** $TSLA: (with video/chart)
**Engagement:** Views: 4,141 | Likes: 10 | Replies: 0 | Reposts: 0 | Bookmarks: 5
**Timestamp:** Sat, 13 Jun 2026 01:24:43 GMT
**Link:** https://x.com/RebellioMarket/status/2065606258485260546
**Sentiment:** Neutral (no text analysis provided; video likely technical).

All posts show meaningful engagement (thousands of views) and real market discussion. No low-engagement posts were included.

In [42]:
print("\n=== Testing Viral Posts (High Engagement Only) ===")
result2 = get_viral_social_posts("TSLA", 5, min_engagement=100)
if 'error' in result2:
    print(f"❌ Error: {result2['error']}")
else:
    print(f"✅ Success - viral posts with 50+ engagement")
    print("Viral posts:")

=== Testing Viral Posts (High Engagement Only) ===
✅ Success - viral posts with 50+ engagement
Viral posts:

In [43]:
print(result1['response'])

**Top 5 posts about $TSLA from the last 24 hours (sorted by highest engagement score = views + likes + replies + reposts):**

**1. Highest engagement**
**Author:** @Realcoinforge
**Content:** 🇺🇸 TESLA HAS JUST SHOWN A MASSIVE BULL SIGNAL BY BREAKING A TRENDLINE. Every time $TSLA broke a trendline on the higher time-frame, it led to a massive expansion. It has just happened again and if the pattern continues, we will see Tesla at $500 real soon. I believe the next 5 years will be game-changing. Tesla has huge plans for the future.
**Engagement:** Views: 13,784 | Likes: 116 | Replies: 5 | Reposts: 7 | Bookmarks: 13
**Timestamp:** Sat, 13 Jun 2026 17:00:16 GMT
**Link:** https://x.com/Realcoinforge/status/2065841698203422976
**Sentiment:** Strongly bullish (highlighting a technical breakout and long-term upside to $500+).

**2.**
**Author:** @peterli34923561
**Content:** $TSLA --- $TSLA has officially disclosed it holds approximately 19 million shares of SpaceX. Valued at $2.56 billion at the IPO price, this is a massive, previously underpriced hidden asset on Tesla’s balance sheet. With the merger of SpaceX and xAI... [full detailed bull thesis on AI, Energy, Robotics, FSD, Optimus, etc., with $600 price target mention].
**Engagement:** Views: 8,168 | Likes: 105 | Replies: 6 | Reposts: 9 | Bookmarks: 26
**Timestamp:** Sat, 13 Jun 2026 03:43:08 GMT
**Link:** https://x.com/peterli34923561/status/2065641088891924697
**Sentiment:** Strongly bullish (emphasizing undervalued assets and massive revaluation potential).

**3.**
**Author:** @BullTradeFinder
**Content:** $TSLA $400 holds you have some upside to $420-$430. OPEX so be careful, things can change quickly. (with chart)
**Engagement:** Views: 6,846 | Likes: 32 | Replies: 2 | Reposts: 0 | Bookmarks: 3
**Timestamp:** Sun, 14 Jun 2026 00:29:09 GMT
**Link:** https://x.com/BullTradeFinder/status/2065954661283062069
**Sentiment:** Bullish (short-term price target with caution on OPEX).

**4.**
**Author:** @SaralTrader
**Content:** $TSLA - Testing patience...Set up is intact, now at breakeven.! Holding Tesla is riding a rollercosater..! (with chart)
**Engagement:** Views: 4,934 | Likes: 36 | Replies: 1 | Reposts: 0 | Bookmarks: 3
**Timestamp:** Sat, 13 Jun 2026 16:27:24 GMT
**Link:** https://x.com/SaralTrader/status/2065833425093722485
**Sentiment:** Neutral-to-bullish (patient holding, setup intact despite volatility).

**5.**
**Author:** @RebellioMarket
**Content:** $TSLA: (with video/chart)
**Engagement:** Views: 4,141 | Likes: 10 | Replies: 0 | Reposts: 0 | Bookmarks: 5
**Timestamp:** Sat, 13 Jun 2026 01:24:43 GMT
**Link:** https://x.com/RebellioMarket/status/2065606258485260546
**Sentiment:** Neutral (no text analysis provided; video likely technical).

All posts show meaningful engagement (thousands of views) and real market discussion. No low-engagement posts were included.

In [44]:
import os
from datetime import datetime
import openai

def get_reddit_stock_discussions(ticker: str, max_posts: int = 5, min_engagement: int = 50):
    """
    Get high-engagement Reddit discussions about a stock using web_search.
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found. Set it in your .envrc file.',
            'posts': []
        }
    
    try:
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        # Reddit-focused search query
        reddit_query = f"""
        Search Reddit for high-quality discussions about ${ticker} stock from the last 7 days.
        
        **TARGET SUBREDDITS (search these specifically):**
        - r/investing (serious investment analysis)
        - r/stocks (general stock discussion)
        - r/SecurityAnalysis (fundamental analysis)
        - r/ValueInvesting (value perspective)
        - r/wallstreetbets (retail sentiment & options)
        - r/StockMarket (market discussion)
        - r/financialindependence (long-term investing)
        - Ticker-specific subs if they exist (like r/Tesla for TSLA)
        
        **ENGAGEMENT CRITERIA:**
        - Posts with {min_engagement}+ upvotes OR 30+ comments
        - Comments with 20+ upvotes
        - Awarded posts (Gold, Silver, Helpful, etc.)
        - Active discussions (not just single comments)
        
        **CONTENT TYPES TO PRIORITIZE:**
        1. DD (Due Diligence) posts with detailed analysis
        2. Earnings reaction/discussion threads
        3. News reaction posts with substantial comments
        4. Technical/fundamental analysis posts
        5. Company catalyst discussions
        6. Valuation debates
        
        **OUTPUT FORMAT for each post:**
        
        **[Subreddit Name]** - Post Title
        **Content:** Brief summary of post + key insights from top comments
        **Stats:** X upvotes, Y comments, Z awards
        **Link:** Direct Reddit URL
        **Sentiment:** Bullish/Bearish/Neutral with reasoning
        **Key Points:** 2-3 main takeaways from the discussion
        **Quality Level:** High/Medium (based on depth of analysis)
        
        Return the {max_posts} most valuable Reddit discussions about ${ticker}, sorted by engagement and discussion quality.
        Focus on posts that provide real investment insights, not just price speculation.
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=reddit_query,
            tools=[{"type": "web_search"}]
        )
        
        # Extract content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'platform': 'Reddit',
            'min_engagement': min_engagement,
            'search_timeframe': 'last_7_days',
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        
    except openai.AuthenticationError:
        return {
            'ticker': ticker,
            'error': 'Authentication failed. Check your XAI_API_KEY.',
            'posts': []
        }
    
    except openai.RateLimitError:
        return {
            'ticker': ticker,
            'error': 'Rate limit exceeded. Try again later.',
            'posts': []
        }
    
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'API error: {str(e)}',
            'posts': []
        }

# Specialized function for DD posts only
def get_reddit_dd_posts(ticker: str, max_posts: int = 3):
    """
    Get only DD (Due Diligence) posts about a stock from Reddit.
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found',
            'posts': []
        }
    
    try:
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        dd_query = f"""
        Search Reddit specifically for DD (Due Diligence) posts about ${ticker} stock.
        
        **SEARCH FOCUS:**
        - Look for posts tagged with "DD" or containing detailed financial analysis
        - Search r/investing, r/SecurityAnalysis, r/ValueInvesting, r/stocks
        - Find posts with comprehensive company analysis, not just opinions
        
        **DD POST CRITERIA:**
        - Contains financial metrics, ratios, or analysis
        - Discusses business fundamentals, competition, or growth prospects
        - Has substantial content (not just a few paragraphs)
        - Generated meaningful discussion in comments
        
        **OUTPUT for each DD post:**
        
        **[Subreddit]** - DD Title
        **Author:** Username (mention if they have credibility/history)
        **Analysis Summary:** Key points from the DD (financials, valuation, thesis)
        **Community Response:** Top comments reactions, counterpoints, additional insights
        **Stats:** Upvotes, comments, awards
        **Link:** Reddit URL
        **Investment Thesis:** Bull/bear case summary
        **Quality Score:** High/Medium/Low based on depth and accuracy
        
        Return the {max_posts} highest quality DD posts about ${ticker} from the last 30 days.
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=dd_query,
            tools=[{"type": "web_search"}]
        )
        
        # Extract content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'search_type': 'dd_posts_only',
            'platform': 'Reddit',
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'Error: {str(e)}',
            'posts': []
        }

In [45]:

# Test the Reddit functions
print("=== Testing Reddit Stock Discussions ===")
result4 = get_reddit_stock_discussions("TSLA", 5, min_engagement=50)

if 'error' in result4:
    print(f"❌ Error: {result4['error']}")
else:
    print(f"✅ Success for {result4['ticker']} on {result4['platform']}")
    print(f"Min engagement: {result4['min_engagement']}")
    print(f"Timeframe: {result4['search_timeframe']}")
    print("\nReddit discussions:")
    print(result4['response'])

=== Testing Reddit Stock Discussions ===
✅ Success for TSLA on Reddit
Min engagement: 50
Timeframe: last_7_days

Reddit discussions:
**Here are the 5 most valuable recent Reddit discussions about $TSLA (from the last 7 days, primarily June 7–14, 2026) that meet the engagement and quality criteria.** Direct standalone TSLA DD, earnings, or analysis threads were limited in the target subreddits during this period. The dominant theme was the SpaceX IPO (around June 12) and frequent comparisons to TSLA’s valuation, with insights on overvaluation, hype vs. fundamentals, PE ratios (~350–400x), and potential merger implications. These provide substantive investment discussion rather than pure price speculation.[[1]](https://www.reddit.com/r/wallstreetbets/comments/1u0bojo/spacex_is_buying_tesla_double_down/)[[2]](https://www.reddit.com/r/investing/comments/1u4lsto/the_math_isnt_mathing_on_the_spacex_ipo/)

**[r/wallstreetbets]** - SpaceX is buying Tesla - Double Down
**Content:** Detailed options strategy betting on a SpaceX acquisition of Tesla (paying a premium in SPCX shares). Outlines Elon’s control motives, AI/robotics alignment, and how it could unlock his TSLA pay package via EBITDA hurdles. Top comments discuss timeline (likely not 2026, possibly mid-next year or later), dilution risks, and historical Elon tactics.
**Stats:** ~1,651 upvotes, 258 comments (highly active).
**Link:** https://www.reddit.com/r/wallstreetbets/comments/1u0bojo/spacex_is_buying_tesla_double_down/
**Sentiment:** Bullish (short-term options play on merger announcement catalyst) with bearish caveats on execution/timeline.
**Key Points:** 1) Merger could tie TSLA more closely to SpaceX’s valuation narrative. 2) Elon prioritizes control over AI/robotics future. 3) High-IV options could spike on news.
**Quality Level:** High (detailed setup with positions and reasoning).[[1]](https://www.reddit.com/r/wallstreetbets/comments/1u0bojo/spacex_is_buying_tesla_double_down/)

**[r/investing]** - The math isn't mathing on the SpaceX IPO
**Content:** Breaks down SpaceX’s ~$2.1T valuation vs. ~$18.7B 2025 revenue (~112x P/S) and losses; repeatedly contrasts with TSLA’s similarly extreme ~370x PE despite being primarily a car company. Top comments reinforce that TSLA’s valuation is “unearned” and not fundamentals-based, comparing it unfavorably to traditional automakers.
**Stats:** High engagement (hundreds of upvotes/comments referenced in thread; active debate).
**Link:** https://www.reddit.com/r/investing/comments/1u4lsto/the_math_isnt_mathing_on_the_spacex_ipo/
**Sentiment:** Bearish on both (TSLA and SpaceX overvalued on hype/vaporware).
**Key Points:** 1) TSLA revenue is ~95% cars, undermining “not just a car company” narrative after a decade+. 2) Extreme multiples persist due to Elon factor/meme status. 3) Parallels suggest SpaceX may follow similar path.
**Quality Level:** High (data-driven valuation critique with community pushback).[[2]](https://www.reddit.com/r/investing/comments/1u4lsto/the_math_isnt_mathing_on_the_spacex_ipo/)

**[r/stocks]** - The "bull case" for SpaceX: re-running the Tesla dilution...
**Content:** Analyzes SpaceX’s proposed ~$1.75T valuation at ~100x P/S despite losses and modest growth; draws direct parallel to TSLA’s history of high multiples during rapid revenue growth phases. Comments note TSLA’s current ~343–395x PE and question sustainability.
**Stats:** Solid engagement (dozens to hundreds of upvotes/comments).
**Link:** https://www.reddit.com/r/stocks/comments/1tzlo3d/the_bull_case_for_spacex_rerunning_the_tesla/
**Sentiment:** Skeptical/bearish on sustainability of such multiples for either company.
**Key Points:** 1) TSLA precedent shows dilution and narrative shifts can sustain high valuations temporarily. 2) SpaceX needs massive growth to justify entry multiple. 3) Retail “Elon factor” drives premiums beyond fundamentals.
**Quality Level:** High (comparative analysis with growth math).[[3]](https://www.reddit.com/r/stocks/comments/1tzlo3d/the_bull_case_for_spacex_rerunning_the_tesla/)

**[r/stocks]** - I am not buying SPCX tomorrow and this is the exact math...
**Content:** Conservative revenue growth projections for SpaceX to justify valuation; multiple comments directly reference TSLA’s ~395–400x PE and how valuation “means nothing” in meme-driven names. Discusses AMD/TSLA parallels for irrational pricing.
**Stats:** Active thread with notable comment volume.
**Link:** https://www.reddit.com/r/stocks/comments/1u3hylp/i_am_not_buying_spcx_tomorrow_and_this_is_the/
**Sentiment:** Bearish on near-term justification but acknowledges momentum can persist.
**Key Points:** 1) TSLA shows markets can ignore traditional metrics for years. 2) Growth assumptions needed for SpaceX/TSLA-like names are aggressive. 3) Retail sentiment overrides math short-term.
**Quality Level:** Medium-High (projections + real-world examples).[[4]](https://www.reddit.com/r/stocks/comments/1u3hylp/i_am_not_buying_spcx_tomorrow_and_this_is_the/)

**[r/stocks]** - People are treating SpaceX like a guaranteed lottery ticket
**Content:** Critiques overvaluation of Elon-linked companies including TSLA (baked-in robotaxi/FSD promises that have soured); notes TSLA’s sideways performance over 5 years despite hype and questions when the “meme stock” correction arrives. Comments debate Reddit’s historical underestimation of TSLA.
**Stats:** Strong discussion volume.
**Link:** https://www.reddit.com/r/stocks/comments/1u33yms/people_are_treating_spacex_like_a_guaranteed/
**Sentiment:** Bearish long-term on hype-driven names like TSLA.
**Key Points:** 1) TSLA valuation relies on unproven future tech amid slowing core business. 2) Government contracts and competition limit SpaceX-like upside. 3) Loyal retail base (“Elon bros”) can delay corrections.
**Quality Level:** Medium-High (narrative and performance analysis).[[5]](https://www.reddit.com/r/stocks/comments/1u33yms/people_are_treating_spacex_like_a_guaranteed/)

**Overall Takeaways:** Discussions heavily frame TSLA through the lens of extreme valuations, unfulfilled promises (robotaxi, autonomy, energy), and the “Elon premium,” with most viewing it as overvalued relative to fundamentals (high PE, car-company reality). Merger speculation with SpaceX adds a potential near-term catalyst angle in retail circles. No major earnings-specific threads appeared in the window. These represent the highest-quality, engaged content available.

In [46]:
print("\n=== Testing DD Posts Only ===")
dd_result = get_reddit_dd_posts("TSLA", 2)

if 'error' in dd_result:
    print(f"❌ Error: {dd_result['error']}")
else:
    print(f"✅ Success - {dd_result['search_type']}")
    print("DD posts preview:")
    print(dd_result['response'])

=== Testing DD Posts Only ===
✅ Success - dd_posts_only
DD posts preview:
**No high-quality DD posts about $TSLA matching the specified criteria were found in the last 30 days (post ~May 15, 2026) across r/stocks, r/investing, r/ValueInvesting, r/SecurityAnalysis, or related subs.**[[1]](https://www.reddit.com/r/stocks/comments/1u2q6vc/spacex_things_to_consider/)

Extensive web searches using site:reddit.com operators, date filters, keywords like "DD", "due diligence", "financial analysis", financial metrics/ratios, and Tesla/TSLA focus returned mostly tangential mentions, comments in unrelated threads (e.g., SpaceX comparisons, general market discussions), daily/earnings threads, or older posts. No posts featured substantial original financial modeling, ratios (e.g., detailed P/E, FCF, valuation multiples with projections), business fundamentals breakdowns, competition analysis, or growth thesis with meaningful comment engagement that met the depth criteria.[[2]](https://www.reddit.com/r/investing/comments/1tuzunv/spacex_valued_at_just_780_billion_by_morningstar/)

Tesla investor subs (e.g., r/teslainvestorsclub) had references to older "full length DD" posts or daily threads, but nothing recent and comprehensive fitting the last-30-days window or the requested subreddits.[[3]](https://www.reddit.com/r/teslainvestorsclub/comments/1kv8a6a/full_length_tesla_dd_and_analysis/)

**Conclusion:** There appear to be zero qualifying DD posts in the timeframe. Searches surfaced general Tesla discussion but nothing with the required financial depth, length, or community response. If new posts emerge or broader searches (including Tesla-specific subs) are needed, provide updated details. Always verify directly on Reddit and do your own due diligence.

# 4) TESTING Edgar and SEC filings
* https://edgartools.readthedocs.io/en/latest/

In [47]:
import os
from edgar import *
set_identity(os.getenv('SEC_IDENTITY_EMAIL'))

In [48]:
company = Company("TSLA")
financials = company.get_financials()
financials.income_statement()

                                         TESLA, INC.   TSLA
                                         CONSOLIDATED STATEMENT OF INCOME
                                         Dec 31, 2023 to Dec 31, 2025

                                                                     Dec 31, 2025   Dec 31, 2024   Dec 31, 2023
   ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
        Revenues
              Revenues:                                                   $94,827        $97,690        $96,773
              Automotive Revenues                                         $69,526        $77,070        $82,419
              Energy generation and storage                                12,771         10,086          6,035
              Services and other                                          $12,530        $10,534         $8,319
        Cost of revenues
              Total cost of revenues:                                     $77,733        $80,240        $79,113
              Automotive Revenues                                         $57,165        $62,873        $66,389
              Energy generation and storage                                 8,969          7,446          4,894
              Services and other                                          $11,599         $9,921         $7,830
            Gross profit:                                                 $17,094        $17,450        $17,660
        Operating expenses
              Research and development                                     $6,411         $4,540         $3,969
              Selling, general and administrative                          $5,834         $5,150         $4,800
              Restructuring and other                                        $494           $684
            Total operating expenses                                      $12,739        $10,374         $8,769
            Income from operations                                          4,355          7,076          8,891
            Interest income                                                $1,680         $1,569         $1,066
            Interest expense                                               $(338)         $(350)         $(156)
            Other (expense) income, net                                    $(419)           $695           $172
            Income before income taxes                                     $5,278         $8,990         $9,973
            Provision for (benefit from) income taxes                      $1,423         $1,837       $(5,001)
            Net income                                                     $3,855         $7,153        $14,974
            Net income (loss) attributable to noncontrolling                  $61            $62          $(23)
    interests and redeemable noncontrolling interests in
    subsidiaries
          Net income attributable to common stockholders                   $3,794         $7,091        $14,997
        Net income per share of common stock attributable to
    common stockholders
            Basic (in dollars per share)                                     1.18           2.23           4.73
            Diluted (in dollars per share)                                   1.08           2.04           4.30
        Weighted average shares used in computing net income per
    share of common stock
            Basic (in shares)                                               3,225          3,197          3,174
            Diluted (in shares)                                             3,528          3,498          3,485

   Source: SEC XBRL  •  (In millions, except shares and per share data)

In [51]:
# Get the latest 10-K filing for the company 
filing = company.get_filings(form="10-K").latest()
text_annual = filing.text()  # Clean, readable text

In [52]:
print(text_annual[0:10000])

UNITED STATES

SECURITIES AND EXCHANGE COMMISSION

Washington, D.C. 20549

FORM 10-K/A

(Amendment No. 1)

(Mark One)

  x       ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
 ────────────────────────────────────────────────────────────────────────────────────────────────

For the fiscal year ended December 31, 2025

OR

  TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
 ────────────────────────────────────────────────────────────────────────────────────────────

For the transition period from

Commission File Number: 001-34756

Tesla, Inc.

(Exact name of registrant as specified in its
charter)

  Texas                                         91-2197729
  (State or other jurisdiction of               (I.R.S. Employer
  1 Tesla Road                                  78725
  (Address of principal executive offices)      (Zip Code)

( 512 516-8177

(Registrant’s telephone number, including
area code)

Securities registered pursuant to Section 12(b) of
the Act:

  Title of each class      Trading Symbol(s)      Name of each exchange on which registered
  Common stock             TSLA                   The Nasdaq Global Select Market
 ─────────────────────────────────────────────────────────────────────────────────────────────

Securities registered pursuant to Section 12(g) of
the Act:

None

Indicate
by check mark whether the registrant is a well-known seasoned issuer, as defined in Rule 405 of the Securities Act.    Yes xNo¨

Indicate
by check mark if the registrant is not required to file reports pursuant to Section 13 or 15(d) of the Act.   Yes   ¨ No x

Indicate
by check mark whether the registrant (1) has filed all reports required to be filed by Section 13 or 15(d) of the Securities
Exchange Act of 1934 (“Exchange Act”) during the preceding 12 months (or for such shorter period that the registrant
was required to file such reports), and (2) has been subject to such filing requirements for the past 90 days.    Yes xNo¨

Indicate
by check mark whether the registrant has submitted electronically every Interactive Data File required to be submitted pursuant to Rule 405
of Regulation S-T (§ 232.405 of this chapter) during the preceding 12 months (or for such shorter period that the registrant
was required to submit such files).    Yes xNo¨

Indicate by check mark whether the registrant
is a large accelerated filer, an accelerated filer, a non-accelerated filer, a smaller reporting company or an emerging growth company.
See the definitions of “large accelerated filer,” “accelerated filer,” “smaller reporting company”
and “emerging growth company” in Rule 12b-2 of the Exchange Act:

  Large accelerated filer      Accelerated filer
  Non-accelerated filer        Smaller reporting company
 ──────────────────────────────────────────────────────────
  Emerging growth company

If an emerging growth company, indicate by check
mark if the registrant has elected not to use the extended transition period for complying with any new or revised financial accounting
standards provided pursuant to Section 13(a) of the Exchange Act. ¨

Indicate by check mark whether the Registrant
has filed a report on and attestation to its management’s assessment of the effectiveness of its internal control over financial
reporting under Section 404(b) of the Sarbanes-Oxley Act (15 U.S.C. 7262(b)) by the registered public accounting firm that
prepared or issued its audit report. x

If securities are registered pursuant to Section
12(b) of the Act, indicate by check mark whether the financial statements of the registrant included in the filing reflect the correction
of an error to previously issued financial statements. ¨

Indicate by check mark whether any of those error
corrections are restatements that required a recovery analysis of incentive-based compensation received by any of the registrant’s
executive officers during the relevant recovery period pursuant to §240.10D-1(b). ¨

Indicate
by check mark whether the registrant is a shell company (as defined in Rule 12b-2 of the Exchange Act).   Yes   ¨No x

The aggregate market value of voting stock
held by non-affiliates of the registrant, as of June 30, 2025, the last business day of the registrant’s most recently
completed second fiscal quarter, was $892.93billion
(based on the closing price for shares of the registrant’s Common Stock as reported by the Nasdaq Global Select Market on
June 30, 2025). Shares of Common Stock held by each executive officer and director have been excluded in that such persons may
be deemed to be affiliates. This determination of affiliate status is not necessarily a conclusive determination for other
purposes.

As of January 23, 2026, there were3,752,431,984shares of the registrant’s Common Stock outstanding.

  Auditor Name: PricewaterhouseCoopers LLP      Auditor Location: San Jose, California      Auditor Firm ID: 238
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────

EXPLANATORY NOTE

On January 29, 2026, Tesla, Inc. (“Tesla,”
the “Company,” “we,” “us,” or “our”) filed ourAnnual Report on Form 10-K for the fiscal year ended December 31, 2025(the “Original Form 10-K”). The Original Form 10-K omitted Part III, Items
10 (Directors, Executive Officers and Corporate Governance), 11 (Executive Compensation), 12 ( Security Ownership of Certain
Beneficial Owners and Management and Related Stockholder Matters), 13 (Certain Relationships and Related Transactions, and Director
Independence) and 14 ( Principal Accountant Fees and Services) in reliance on General Instruction G(3) to Form 10-K,
which provides that such information may be either incorporated by reference from the registrant’s definitive proxy statement or
included in an amendment to Form 10-K, in either case filed with the Securities and Exchange Commission (the “SEC”) not
later than 120 days after the end of the fiscal year.

T he
Board of Directors has not yet established the date of the 2026 annual meeting of shareholders. When the date is established, the Company
will announce it in its filings made with the SEC. Consequently, we currently expect that our definitive proxy statement for the 2026
annual meeting of shareholders will be filed later than the 120 th

  amend Part III, Items 10, 11, 12, 13 and 14 of the Original Form 10-K to include the information required by such Items;
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  delete the reference on the cover of the Original Form 10-K to the incorporation by reference of portions of our proxy statement

  file new certifications of our principal executive officer and principal financial officer as exhibits to this Amendment under Item 15
  of Part IV hereof, pursuant to Rule 12b-15 under the Securities Exchange Act of 1934, as amended (the “Exchange Act”).
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

This Amendment does not otherwise change or update
any of the disclosures set forth in the Original Form 10-K and, except as otherwise noted, does not otherwise reflect any events occurring after the filing of
the Original Form 10-K.

TESLA, INC.

AMENDMENT NO. 1 TO ANNUAL REPORT ON FORM 10-K/A

FOR THE YEAR ENDED DECEMBER 31, 2025

INDEX

                                                                                                                             Page
  EXPLANATORY NOTE.
  PART III.                                                                                                                     1
  Item 10.               Directors, Executive Officers and Corporate Governance                                                 1
  Item 11.               Executive Compensation                                                                                 5
  Item 12.               Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters        26
  Item 13.               Certain Relationships and Related Transactions and Director Independence                              28
  Item 14.               Principal Accountant Fees and Services                                                                29
  PART IV.                                                                                                                     31
  Item 15.               Exhibits and Financial Statement Schedules                                                            31
  Signatures                                                                                                                   37

PART III

ITEM 10.     DIRECTORS, EXECUTIVE
OFFICERS AND CORPORATE GOVERNANCE

Background and Qualifications

The names of the members of Tesla’s Board
of Directors (the “Board”), their respective ages, their positions with Tesla and other biographical information as of April 30,
2026, are set forth below. Except for Messrs. Elon Musk and Kimbal Musk, who are brothers, there are no other family relationships
among any of our directors or executive officers.

                                                                                           Nominating
                                                                                           and
                                                                                           Corporate       Disclosure      Term
                                        Chair of the      Audit

In [53]:
filing = company.get_filings(form="10-Q").latest()
text_quarterly = filing.text()  # Clean, readable text

In [54]:
# Initialize OpenAI client - OPENAI_API_KEY env. variable must be set in the .envrc file
client = openai.OpenAI()

In [55]:
# Use a portion of the text to stay within context limits if necessary
# The current 'text' variable holds the latest 10-Q filing from previous cells
input_text = text_annual

response = client.chat.completions.create(
    model="gpt-5.4-mini",
    messages=[
        {"role": "system", "content": "You are a financial analyst."},
        {"role": "user", "content": f"Analyze the following company filing and identify what is new or significant compared to previous periods. Here is the text: {input_text}"}
    ]
)

print(response.choices[0].message.content)

Here are the main **new or significant items** in this 10-K/A versus prior periods and Tesla’s earlier disclosures:

## 1) This amendment is primarily a Part III “late proxy” filing
- Tesla filed its original 2025 10-K on Jan. 29, 2026, but omitted **Part III** because the proxy statement was not ready.
- This 10-K/A adds:
  - **Directors / executive officers / governance**
  - **Executive compensation**
  - **Ownership**
  - **Related-party transactions**
  - **Auditor fees**
- Tesla also filed **new CEO/CFO certifications** with the amendment.

## 2) Major new board and leadership changes
### New director: **Jack Hartung**
- Added to the board in **June 2025**.
- Former senior advisor / president at **Chipotle**.
- Notable because this is a relatively new director with strong finance, strategy, and operations credentials.

### Board / committee structure update
- The board now includes Jack Hartung on the **Audit Committee**.
- Tesla’s disclosure confirms the board still has four standing committees and that **Robyn Denholm** is audit committee chair and financial expert.

## 3) Elon Musk’s biography has several significant updates
Tesla added material new background regarding Musk’s outside roles:
- He was involved in the **March 2025 merger of X and xAI**.
- After that merger, he served as President, Treasurer and CEO of **xAI Holdings**.
- **xAI Holdings became a subsidiary of SpaceX in February 2026**.
- Tesla also added disclosure about the **April 2026 partial judgment in Pampena v. Musk** relating to Twitter/X statements.

This is significant because it reflects:
- Musk’s expanding private-company ecosystem
- More overlap between Tesla and Musk-controlled affiliates
- A new litigation disclosure that did not exist in prior annual reports

## 4) Very large new CEO compensation awards in 2025
This is the biggest substantive new item in the filing.

### 2025 CEO Interim Award
- In **August 2025**, Tesla granted Musk **96 million shares of restricted stock**.
- Grant-date fair value disclosed: **$26.06 billion**
- It was intended as an interim retention/incentive award.
- **It was forfeited in full in April 2026** after the reinstatement of the 2018 award.

### 2025 CEO Performance Award
- In **September 2025**, Tesla granted Musk **423,743,904 shares of performance-based restricted stock**.
- Shareholders approved it in **November 2025**.
- Maximum grant-date fair value disclosed: **$132.3 billion**
- This is an extraordinary new incentive structure with:
  - **12 tranches**
  - Market-cap milestones from **$2 trillion to $8.5 trillion**
  - Operational milestones tied to:
    - 20 million vehicle deliveries
    - 10 million active FSD subscriptions
    - 1 million bots delivered
    - 1 million robotaxis in commercial operation
    - massive Adjusted EBITDA targets up to $400 billion

### Why this matters
This is far more aggressive and unusual than prior periods:
- It dwarfs prior compensation disclosures
- It links Musk’s pay to Tesla’s transformation into an **AI / robotics / autonomy company**
- It creates an unprecedented alignment structure based on extreme long-term market cap and operating targets

## 5) The 2018 CEO Performance Award was effectively revived and implemented
This is a major legal and compensation development.

- Tesla says the **Delaware Supreme Court reversed the rescission** of the 2018 CEO Performance Award in December 2025.
- Tesla also states that by the date of this filing, **all 12 tranches had vested and become exercisable**.
- Tesla entered into the **Implementation Agreement** on April 21, 2026, creating a process for Musk to exercise the award.
- The agreement imposes:
  - service-based vesting through **January 19, 2028**
  - a **five-year holding period**
  - tax and net settlement mechanics

### Significance
This changes the economics of one of the most heavily litigated executive awards in U.S. corporate history.

## 6) Reported CEO compensation is extraordinarily large, but mostly accounting-based
Tesla discloses:
- **2025 reported total CEO compensation:** **$158.36 billion**
- Median employee total compensation: **$62,786**
- Reported pay ratio: **2,522,203:1**

Tesla also adds a separate “realized compensation” presentation:
- 2025 realized CEO compensation: effectively **$0** in the ratio table
- This is meant to highlight that the reported figure is largely ASC 718 grant-date accounting value, not cash actually received

### Why this is significant
- The reported CEO compensation is unprecedented
- Tesla is explicitly trying to frame the number as an accounting construct rather than economic cash pay
- It underscores how compensation reporting can diverge dramatically from realized value

## 7) Executive compensation program remained heavily equity-based
Compared with prior periods, Tesla reiterates and reinforces:
- No cash bonuses
- No non-equity incentive plan compensation
- Limited perquisites
- Executive pay remains primarily **salary + long-term equity**
- Outside directors also continue to forgo cash retainer payments

For the other NEOs:
- **Vaibhav Taneja** salary was **$400,000**
- **Tom Zhu** salary was **$364,338**
- Their compensation remains modest relative to Musk’s

## 8) Compensation Committee and special committee governance is a key new feature
Tesla discloses that in 2025:
- The board formed a **Special Committee** of disinterested directors
- It was tasked with deciding how to retain and incentivize Musk
- **Compensia** was retained as consultant for the 2025 CEO Performance Award

This is important because it shows:
- Tesla used a special governance process for Musk comp
- The award was not handled through the ordinary compensation committee process alone

## 9) New related-party investment in xAI Holdings / SpaceX
Tesla disclosed a **new $2.0 billion investment**:
- On Jan. 16, 2026 Tesla agreed to invest about **$2.0 billion** in xAI Holdings
- After the merger, the investment converted into a right to acquire **SpaceX Class A common stock**
- Tesla completed the investment on **March 12, 2026**

### Why this matters
This is a meaningful new related-party transaction involving:
- Musk-controlled entities
- strategic exposure to SpaceX
- growing complexity in Tesla’s related-party ecosystem

## 10) Related-party revenues and expenses increased/continued across Musk-linked companies
Tesla disclosed ongoing business with:
- **SpaceX**
- **xAI**
- **X**
- **The Boring Company**
- Musk’s security company
- **Redwood Materials** via JB Straubel

Particularly notable:
- Tesla recognized **$430.1 million of revenue from xAI in 2025**
- Tesla recognized **$143.3 million of revenue from SpaceX in 2025**
- Tesla also booked **$12.9 million** as a reduction of cost of revenues from scrap sales to Redwood

This is notable because it shows Tesla’s commercial relationships with founder-linked private companies are economically material, not just incidental.

## 11) New governance / ownership disclosure updates
### Ownership
- Musk beneficially owns **717.1 million shares**, or **20.3%**
- The group of all directors and executive officers owns **20.5%**
- Vanguard’s disclosure changed due to an internal realignment, which Tesla notes for future reporting

### Director compensation
- No cash or new option compensation was paid to non-employee directors in 2025
- Tesla explains that directors had previously waived compensation under the Detroit settlement-related arrangements

## 12) Audit fees rose modestly
PwC fees increased slightly:
- Audit fees: **$15.6M → $16.5M**
- Total fees: **$17.9M → $18.1M**
- Tax fees declined from **$2.15M to $1.40M**

This is not a major story, but it is a notable year-over-year change.

---

## Bottom line
The filing’s most important new developments are:

1. **Tesla’s enormous new CEO compensation structure for Musk**
2. **The 2018 CEO award litigation reversal and implementation agreement**
3. **New related-party investment in xAI Holdings / SpaceX**
4. **New litigation disclosure involving Musk**
5. **Addition of Jack Hartung to the board**
6. **A stronger disclosure push toward Tesla’s AI/robotics/autonomy identity**

If you want, I can also turn this into a **short investor-focused bullet summary** or a **“what changed vs 2024 10-K” comparison table**.

In [67]:
def get_usage_info_chatcompletion(response):
    """
    Extract usage information and estimate API cost from a ChatCompletion response.
    """

    # GPT-5.4-mini pricing
    INPUT_PRICE = 0.75 / 1_000_000
    OUTPUT_PRICE = 4.50 / 1_000_000

    if not hasattr(response, "usage") or response.usage is None:
        return {"error": "Usage information not available."}

    usage = response.usage

    input_tokens = usage.prompt_tokens
    output_tokens = usage.completion_tokens

    return {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": usage.total_tokens,
        "cost_usd": (
            input_tokens * INPUT_PRICE +
            output_tokens * OUTPUT_PRICE
        ),
        "prompt_tokens_details": (
            usage.prompt_tokens_details.model_dump()
            if hasattr(usage.prompt_tokens_details, "model_dump")
            else None
        ),
        "completion_tokens_details": (
            usage.completion_tokens_details.model_dump()
            if hasattr(usage.completion_tokens_details, "model_dump")
            else None
        ),
    }

In [68]:
# $0.03 cost of analysis
get_usage_info_chatcompletion(response)

{'input_tokens': 30673,
 'output_tokens': 1883,
 'total_tokens': 32556,
 'cost_usd': 0.03147825,
 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0},
 'completion_tokens_details': {'accepted_prediction_tokens': 0,
  'audio_tokens': 0,
  'reasoning_tokens': 0,
  'rejected_prediction_tokens': 0}}

In [72]:
# Use a portion of the text to stay within context limits if necessary
# The current 'text' variable holds the latest 10-Q filing from previous cells
input_text_quarterly = text_quarterly
input_text_annual = text_annual


response_full = client.chat.completions.create(
    model="gpt-5.4-mini",
    messages=[
        {"role": "system", "content": "You are a financial analyst."},
        {"role": "user", "content": f"Analyze the following company filing and identify what is new or significant compared to previous periods. \
          Here is the latest quarterly text: {input_text_quarterly}. Here is the latest annual report released earlier: {input_text_annual}.\
          Turn this into a **“new vs. prior period” table** with columns for **change / financial impact / why it matters. Provide a concise summary of the key points and any potential implications for investors."}
    ]
)

print(response_full.choices[0].message.content)

Below is a concise **new vs. prior period** table highlighting what changed in Tesla’s **Q1 2026 10-Q** versus **Q1 2025** and, where relevant, versus **year-end 2025**. I’ve focused on items that are **new, materially different, or strategically significant**.

## Tesla Q1 2026: New vs. Prior Period

| Change | Financial impact | Why it matters |
|---|---:|---|
| **Revenue reaccelerated to $22.4B, up 16% YoY** | +$3.05B revenue | Top-line growth improved, driven mainly by higher automotive sales and services. |
| **Automotive sales rose 20% YoY** | +$2.55B | Suggests higher deliveries and better average selling price; management said deliveries rose ~10% and pricing improved from mix and FX. |
| **Regulatory credits fell 36% YoY** | -$215M | Tesla is becoming less reliant on credit sales; good if core auto profitability is improving, but it removes a margin-supporting revenue source. |
| **Services and other revenue jumped 42% YoY** | +$1.11B | Strong growth in used vehicle sales, maintenance, Supercharging, and insurance indicates the ecosystem business is expanding. |
| **Energy generation & storage revenue declined 12% YoY** | -$322M | A softer energy quarter, likely from lower Megapack/Powerwall deployments; important because this is a key growth segment. |
| **Gross margin improved sharply to 21.1% from 16.3%** | +4.8 pts total gross margin | Indicates better pricing, mix, and/or cost control; a major positive for profitability. |
| **Automotive gross margin improved to 21.1% from 16.2%** | +4.9 pts | Shows core auto profitability improved materially even with lower regulatory credits. |
| **Energy gross margin rose to 39.5% from 28.8%** | +10.7 pts | Suggests much better unit economics in energy, despite lower revenue. |
| **Operating income more than doubled to $941M** | +$542M | Indicates operating leverage is improving. |
| **R&D increased 38% YoY** | +$537M | Tesla is spending more on AI, autonomy, robotics, and new programs; this is strategically important but raises near-term expense load. |
| **SG&A increased 47% YoY** | +$582M | Driven by stock comp, labor, and legal costs. This is a margin headwind and may persist if legal/compensation costs remain elevated. |
| **Other expense, net worsened sharply** | -$416M vs. prior year | Mainly foreign exchange losses and digital asset mark-to-market losses; adds earnings volatility. |
| **Effective tax rate increased to 34% from 29%** | Higher tax expense (+$88M tax provision) | Partly due to jurisdiction mix and non-deductibility of stock comp tied to CEO awards; reduces bottom-line conversion. |
| **Operating cash flow improved to $3.94B** | +$1.78B YoY | Strong cash generation supports capex and AI investment plans. |
| **Capex rose to $2.49B** | +$1.00B YoY | Tesla is spending more on AI infrastructure, manufacturing, and factory expansion; signals aggressive investment mode. |
| **Tesla bought $2.0B of SpaceX equity** | New investing cash outflow of $2.0B | This is a major new related-party investment and a notable use of cash; investors may view it as strategic but non-core. |
| **Debt structure changed significantly** | Total debt/finance leases fell to $9.23B from $8.39B? (note: balance sheet current+LT debt/leases rose to $9.23B from $8.38B) | Tesla increased financing activity in Q1 2026, including new debt proceeds and a new warehouse facility. |
| **New Warehouse Agreement entered in Q1 2026** | Potential borrowing capacity up to $1.5B | Expands financing flexibility; could support vehicle/asset-backed funding needs. |
| **2018 CEO Performance Award reinstated/implemented** | No new P&L expense for 2018 award, but major governance impact | A major corporate governance event: Tesla and Elon Musk entered the “Implementation Agreement,” changing how the award can be exercised. |
| **2025 CEO Interim Award forfeited in April 2026** | Removes a previously disclosed $26.1B grant-date accounting value from future compensation discussions | This is a major compensation and governance update. It eliminates a potentially massive outstanding CEO award. |
| **2025 CEO Performance Award remains outstanding; no tranches earned yet** | No current cash impact, but large potential future dilution/comp | Still one of the largest contingent compensation awards ever disclosed; important for dilution and governance scrutiny. |
| **New acquisition agreement for an AI hardware company** | Up to $2.0B in Tesla stock/equity awards (mostly service/performance contingent) | Signals continued push into AI hardware/compute; could expand capabilities but adds integration and execution risk. |
| **Tariff ruling may allow refunds** | Potential future benefit, not yet recognized | If recovered, could lower costs or increase income, but timing/amount is uncertain. |
| **Legal proceedings progressed** | Several cases resolved or advanced; no single quantified new reserve disclosed | Notable developments: Delaware derivative settlement affirmed and fee award reduced; some suits dismissed or moving toward trial; continued litigation risk remains. |

---

## Key new / significant items by category

### 1) Business performance
- **Revenue, gross profit, operating income, and operating cash flow all improved.**
- The main positives were:
  - **higher automotive sales**
  - **much better gross margins**
  - **stronger services revenue**
- The main drag was:
  - **weaker energy revenue**
  - **higher operating expenses**
  - **foreign exchange and digital asset losses**

### 2) Strategic shifts
- Tesla is clearly emphasizing **AI, autonomy, robotics, and compute infrastructure**.
- Management explicitly said it is focused on:
  - **FSD (Supervised)**
  - **Robotaxi/Cybercab**
  - **Optimus**
  - **semiconductor fabrication**
  - **AI data centers / training clusters**
- Capex guidance of **more than $25B in 2026** is a major indicator of this shift.

### 3) Related-party investment
- Tesla invested **$2.0B in SpaceX** in Q1 2026.
- This is significant because it is:
  - a large cash deployment
  - related-party in nature
  - non-core to the automotive business
- Investors may view it as strategically interesting but also as a use of capital outside Tesla’s main operations.

### 4) CEO compensation / governance
This is the biggest governance story in the filing:
- The **2018 CEO Performance Award was reinstated** by the Delaware Supreme Court and then operationalized through a new **Implementation Agreement**.
- The **2025 CEO Interim Award was forfeited** in April 2026.
- Tesla says the Implementation Agreement creates **no additional economic benefit**, but it does impose a **service-based vesting condition** and a **holding period** on shares issued upon exercise.
- This reduces immediate windfall concerns but keeps CEO comp and dilution in focus.

### 5) Financing / balance sheet
- Tesla’s liquidity remains strong:
  - **$44.7B cash + short-term investments**
  - **$5.0B unused committed credit**
- But there are notable movements:
  - new debt issuance
  - repayment activity
  - new warehouse facility
  - higher capex and related investment spending

---

## Investor implications

### Positive takeaways
- **Core profitability improved materially**
- **Operating cash flow strengthened**
- **Services revenue is scaling**
- **Energy gross margin improved sharply**
- **Strong liquidity supports heavy AI and manufacturing investment**

### Watch items / risks
- **Energy revenue weakened**
- **R&D and SG&A are rising quickly**
- **Other expense remains volatile**
- **CEO compensation/governance remains a major overhang**
- **Large AI and robotics spending could pressure near-term free cash flow**
- **Related-party investments and litigation may keep investor scrutiny high**

## Bottom line
Tesla’s Q1 2026 filing is notable for:
1. **better operating performance and margins**,
2. **heavier investment in AI/autonomy/robotics**, and
3. **major CEO compensation/governance developments** that materially change the stock-comp picture.

If you want, I can also convert this into a **bullet-style earnings note**, a **risk/opportunity matrix**, or a **“what changed in the 10-Q vs 10-K” redline summary**.

In [73]:
# readable output in Jupyter Notebook
from IPython.display import Markdown, display
display(Markdown(response_full.choices[0].message.content))

Below is a concise **new vs. prior period** table highlighting what changed in Tesla’s **Q1 2026 10-Q** versus **Q1 2025** and, where relevant, versus **year-end 2025**. I’ve focused on items that are **new, materially different, or strategically significant**.

## Tesla Q1 2026: New vs. Prior Period

| Change | Financial impact | Why it matters |
|---|---:|---|
| **Revenue reaccelerated to $22.4B, up 16% YoY** | +$3.05B revenue | Top-line growth improved, driven mainly by higher automotive sales and services. |
| **Automotive sales rose 20% YoY** | +$2.55B | Suggests higher deliveries and better average selling price; management said deliveries rose ~10% and pricing improved from mix and FX. |
| **Regulatory credits fell 36% YoY** | -$215M | Tesla is becoming less reliant on credit sales; good if core auto profitability is improving, but it removes a margin-supporting revenue source. |
| **Services and other revenue jumped 42% YoY** | +$1.11B | Strong growth in used vehicle sales, maintenance, Supercharging, and insurance indicates the ecosystem business is expanding. |
| **Energy generation & storage revenue declined 12% YoY** | -$322M | A softer energy quarter, likely from lower Megapack/Powerwall deployments; important because this is a key growth segment. |
| **Gross margin improved sharply to 21.1% from 16.3%** | +4.8 pts total gross margin | Indicates better pricing, mix, and/or cost control; a major positive for profitability. |
| **Automotive gross margin improved to 21.1% from 16.2%** | +4.9 pts | Shows core auto profitability improved materially even with lower regulatory credits. |
| **Energy gross margin rose to 39.5% from 28.8%** | +10.7 pts | Suggests much better unit economics in energy, despite lower revenue. |
| **Operating income more than doubled to $941M** | +$542M | Indicates operating leverage is improving. |
| **R&D increased 38% YoY** | +$537M | Tesla is spending more on AI, autonomy, robotics, and new programs; this is strategically important but raises near-term expense load. |
| **SG&A increased 47% YoY** | +$582M | Driven by stock comp, labor, and legal costs. This is a margin headwind and may persist if legal/compensation costs remain elevated. |
| **Other expense, net worsened sharply** | -$416M vs. prior year | Mainly foreign exchange losses and digital asset mark-to-market losses; adds earnings volatility. |
| **Effective tax rate increased to 34% from 29%** | Higher tax expense (+$88M tax provision) | Partly due to jurisdiction mix and non-deductibility of stock comp tied to CEO awards; reduces bottom-line conversion. |
| **Operating cash flow improved to $3.94B** | +$1.78B YoY | Strong cash generation supports capex and AI investment plans. |
| **Capex rose to $2.49B** | +$1.00B YoY | Tesla is spending more on AI infrastructure, manufacturing, and factory expansion; signals aggressive investment mode. |
| **Tesla bought $2.0B of SpaceX equity** | New investing cash outflow of $2.0B | This is a major new related-party investment and a notable use of cash; investors may view it as strategic but non-core. |
| **Debt structure changed significantly** | Total debt/finance leases fell to $9.23B from $8.39B? (note: balance sheet current+LT debt/leases rose to $9.23B from $8.38B) | Tesla increased financing activity in Q1 2026, including new debt proceeds and a new warehouse facility. |
| **New Warehouse Agreement entered in Q1 2026** | Potential borrowing capacity up to $1.5B | Expands financing flexibility; could support vehicle/asset-backed funding needs. |
| **2018 CEO Performance Award reinstated/implemented** | No new P&L expense for 2018 award, but major governance impact | A major corporate governance event: Tesla and Elon Musk entered the “Implementation Agreement,” changing how the award can be exercised. |
| **2025 CEO Interim Award forfeited in April 2026** | Removes a previously disclosed $26.1B grant-date accounting value from future compensation discussions | This is a major compensation and governance update. It eliminates a potentially massive outstanding CEO award. |
| **2025 CEO Performance Award remains outstanding; no tranches earned yet** | No current cash impact, but large potential future dilution/comp | Still one of the largest contingent compensation awards ever disclosed; important for dilution and governance scrutiny. |
| **New acquisition agreement for an AI hardware company** | Up to $2.0B in Tesla stock/equity awards (mostly service/performance contingent) | Signals continued push into AI hardware/compute; could expand capabilities but adds integration and execution risk. |
| **Tariff ruling may allow refunds** | Potential future benefit, not yet recognized | If recovered, could lower costs or increase income, but timing/amount is uncertain. |
| **Legal proceedings progressed** | Several cases resolved or advanced; no single quantified new reserve disclosed | Notable developments: Delaware derivative settlement affirmed and fee award reduced; some suits dismissed or moving toward trial; continued litigation risk remains. |

---

## Key new / significant items by category

### 1) Business performance
- **Revenue, gross profit, operating income, and operating cash flow all improved.**
- The main positives were:
  - **higher automotive sales**
  - **much better gross margins**
  - **stronger services revenue**
- The main drag was:
  - **weaker energy revenue**
  - **higher operating expenses**
  - **foreign exchange and digital asset losses**

### 2) Strategic shifts
- Tesla is clearly emphasizing **AI, autonomy, robotics, and compute infrastructure**.
- Management explicitly said it is focused on:
  - **FSD (Supervised)**
  - **Robotaxi/Cybercab**
  - **Optimus**
  - **semiconductor fabrication**
  - **AI data centers / training clusters**
- Capex guidance of **more than $25B in 2026** is a major indicator of this shift.

### 3) Related-party investment
- Tesla invested **$2.0B in SpaceX** in Q1 2026.
- This is significant because it is:
  - a large cash deployment
  - related-party in nature
  - non-core to the automotive business
- Investors may view it as strategically interesting but also as a use of capital outside Tesla’s main operations.

### 4) CEO compensation / governance
This is the biggest governance story in the filing:
- The **2018 CEO Performance Award was reinstated** by the Delaware Supreme Court and then operationalized through a new **Implementation Agreement**.
- The **2025 CEO Interim Award was forfeited** in April 2026.
- Tesla says the Implementation Agreement creates **no additional economic benefit**, but it does impose a **service-based vesting condition** and a **holding period** on shares issued upon exercise.
- This reduces immediate windfall concerns but keeps CEO comp and dilution in focus.

### 5) Financing / balance sheet
- Tesla’s liquidity remains strong:
  - **$44.7B cash + short-term investments**
  - **$5.0B unused committed credit**
- But there are notable movements:
  - new debt issuance
  - repayment activity
  - new warehouse facility
  - higher capex and related investment spending

---

## Investor implications

### Positive takeaways
- **Core profitability improved materially**
- **Operating cash flow strengthened**
- **Services revenue is scaling**
- **Energy gross margin improved sharply**
- **Strong liquidity supports heavy AI and manufacturing investment**

### Watch items / risks
- **Energy revenue weakened**
- **R&D and SG&A are rising quickly**
- **Other expense remains volatile**
- **CEO compensation/governance remains a major overhang**
- **Large AI and robotics spending could pressure near-term free cash flow**
- **Related-party investments and litigation may keep investor scrutiny high**

## Bottom line
Tesla’s Q1 2026 filing is notable for:
1. **better operating performance and margins**,
2. **heavier investment in AI/autonomy/robotics**, and
3. **major CEO compensation/governance developments** that materially change the stock-comp picture.

If you want, I can also convert this into a **bullet-style earnings note**, a **risk/opportunity matrix**, or a **“what changed in the 10-Q vs 10-K” redline summary**.

In [74]:
# $0.05 cost of analysis
get_usage_info_chatcompletion(response_full)

{'input_tokens': 56633,
 'output_tokens': 1896,
 'total_tokens': 58529,
 'cost_usd': 0.05100675,
 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0},
 'completion_tokens_details': {'accepted_prediction_tokens': 0,
  'audio_tokens': 0,
  'reasoning_tokens': 0,
  'rejected_prediction_tokens': 0}}